import type { Xiehouyu } from './types'

const DATA: Xiehouyu[] = [
  // ===== Easy (1-30) =====
  { id: 1, front: '竹篮打水', back: '一场空', options: ['一场空', '白费力气', '徒劳无功', '水到渠成'], explanation: '竹篮有孔漏水，打水最后什么也留不下。', difficulty: 'easy' },
  { id: 2, front: '铁公鸡', back: '一毛不拔', options: ['一毛不拔', '铁面无私', '坚如磐石', '冷酷无情'], explanation: '铁做的公鸡，一根毛也拔不出来，形容极度吝啬。', difficulty: 'easy' },
  { id: 3, front: '泥菩萨过河', back: '自身难保', options: ['自身难保', '步步艰难', '随波逐流', '水深火热'], explanation: '泥做的菩萨过河会融化，自己都保不住。', difficulty: 'easy' },
  { id: 4, front: '哑巴吃黄连', back: '有苦说不出', options: ['有苦说不出', '苦不堪言', '哑口无言', '苦尽甘来'], explanation: '哑巴不能说话，吃了苦的黄连也无法表达。', difficulty: 'easy' },
  { id: 5, front: '猪八戒照镜子', back: '里外不是人', options: ['里外不是人', '丑态百出', '自讨没趣', '面目可憎'], explanation: '猪八戒照镜子，镜子里外都不是人的模样。', difficulty: 'easy' },
  { id: 6, front: '热锅上的蚂蚁', back: '团团转', options: ['团团转', '急得团团转', '走投无路', '惊慌失措'], explanation: '蚂蚁在热锅上四处乱转，形容焦急万分。', difficulty: 'easy' },
  { id: 7, front: '千里送鹅毛', back: '礼轻情意重', options: ['礼轻情意重', '鹅毛大雪', '远道而来', '物轻意重'], explanation: '千里之外送一根鹅毛，礼物虽轻但情意深厚。', difficulty: 'easy' },
  { id: 8, front: '肉包子打狗', back: '有去无回', options: ['有去无回', '一去不返', '白费力气', '得不偿失'], explanation: '用肉包子打狗，狗吃了包子不会还回来。', difficulty: 'easy' },
  { id: 9, front: '王婆卖瓜', back: '自卖自夸', options: ['自卖自夸', '货真价实', '夸夸其谈', '口蜜腹剑'], explanation: '王婆卖自己的瓜，自然说自己瓜好。', difficulty: 'easy' },
  { id: 10, front: '老虎拉车', back: '谁敢', options: ['谁敢', '横行霸道', '力大无穷', '无人敢拦'], explanation: '老虎拉车——谁敢（去拦）？谐音"谁赶"。', difficulty: 'easy' },
  { id: 11, front: '小葱拌豆腐', back: '一清二白', options: ['一清二白', '清清楚楚', '白璧无瑕', '黑白分明'], explanation: '小葱绿豆腐白，拌在一起青白分明。', difficulty: 'easy' },
  { id: 12, front: '鸡蛋碰石头', back: '不自量力', options: ['不自量力', '粉身碎骨', '硬碰硬', '以卵击石'], explanation: '鸡蛋碰石头，根本不是对手。', difficulty: 'easy' },
  { id: 13, front: '狗咬吕洞宾', back: '不识好人心', options: ['不识好人心', '狗仗人势', '恩将仇报', '以怨报德'], explanation: '吕洞宾是好心人，狗却咬他，形容不识好人。', difficulty: 'easy' },
  { id: 14, front: '骑驴看唱本', back: '走着瞧', options: ['走着瞧', '慢慢看', '走着看戏', '边走边唱'], explanation: '骑驴边走边看戏本——走着瞧（边走边看）。', difficulty: 'easy' },
  { id: 15, front: '猫哭耗子', back: '假慈悲', options: ['假慈悲', '虚情假意', '猫鼠同眠', '装模作样'], explanation: '猫哭老鼠死，不是真伤心而是假慈悲。', difficulty: 'easy' },
  { id: 16, front: '黄鼠狼给鸡拜年', back: '没安好心', options: ['没安好心', '居心叵测', '虚情假意', '心怀鬼胎'], explanation: '黄鼠狼拜年是为了吃鸡，不是真有好意。', difficulty: 'easy' },
  { id: 17, front: '秀才遇到兵', back: '有理说不清', options: ['有理说不清', '秀才不出门', '兵荒马乱', '秀才造反'], explanation: '秀才讲道理但兵不听，有理也说不清。', difficulty: 'easy' },
  { id: 18, front: '老鼠过街', back: '人人喊打', options: ['人人喊打', '胆小如鼠', '落荒而逃', '鬼鬼祟祟'], explanation: '老鼠过街，人人都要打它。', difficulty: 'easy' },
  { id: 19, front: '瞎子点灯', back: '白费蜡', options: ['白费蜡', '照不见路', '浪费光阴', '徒劳无功'], explanation: '瞎子看不见，点灯白浪费蜡烛。', difficulty: 'easy' },
  { id: 20, front: '老虎头上拔毛', back: '不知死', options: ['不知死', '胆大包天', '找死', '冒险犯难'], explanation: '老虎头上拔毛，太危险了等于找死。', difficulty: 'easy' },
  { id: 21, front: '芝麻开花', back: '节节高', options: ['节节高', '芝麻小事', '芝麻绿豆', '步步高升'], explanation: '芝麻开花一节比一节高，比喻越来越好。', difficulty: 'easy' },
  { id: 22, front: '大海捞针', back: '无处寻', options: ['无处寻', '难上加难', '渺茫无望', '千辛万苦'], explanation: '大海捞针根本找不到。', difficulty: 'easy' },
  { id: 23, front: '三个臭皮匠', back: '顶个诸葛亮', options: ['顶个诸葛亮', '人多力量大', '臭味相投', '人多嘴杂'], explanation: '三个普通人合起来能抵一个诸葛亮。', difficulty: 'easy' },
  { id: 24, front: '十五个吊桶打水', back: '七上八下', options: ['七上八下', '忙忙碌碌', '上下不定', '慌慌张张'], explanation: '十五个吊桶七个上八个下，形容心神不定。', difficulty: 'easy' },
  { id: 25, front: '螳臂挡车', back: '不自量力', options: ['不自量力', '自取灭亡', '螳螂捕蝉', '力不从心'], explanation: '螳螂挡车，力量太小不自量力。', difficulty: 'easy' },
  { id: 26, front: '司马昭之心', back: '路人皆知', options: ['路人皆知', '天下闻名', '居心叵测', '明目张胆'], explanation: '司马昭想篡位的心思，路人都知道了。', difficulty: 'easy' },
  { id: 27, front: '吃力不讨好', back: '白费劲', options: ['白费劲', '得不偿失', '费力不讨好', '徒劳无功'], explanation: '费了力气却没得到好结果。', difficulty: 'easy' },
  { id: 28, front: '外甥打灯笼', back: '照舅', options: ['照舅', '找旧', '照旧', '旧事重提'], explanation: '"照舅"谐音"照旧"，还是老样子。', difficulty: 'easy' },
  { id: 29, front: '猴子捞月', back: '一场空', options: ['一场空', '白忙一场', '空欢喜', '徒劳无功'], explanation: '猴子捞水中月亮，捞不上来。', difficulty: 'easy' },
  { id: 30, front: '雷公打豆腐', back: '拣软的欺', options: ['拣软的欺', '避硬就软', '欺软怕硬', '专挑弱点'], explanation: '雷公打豆腐挑软的打，形容欺软怕硬。', difficulty: 'easy' },

  // ===== Medium (31-65) =====
  { id: 31, front: '盲人摸象', back: '不识大体', options: ['不识大体', '一叶障目', '摸不着头脑', '瞎猜瞎想'], explanation: '盲人摸象只摸到一部分就下结论，看不清整体。', difficulty: 'medium' },
  { id: 32, front: '飞蛾扑火', back: '自取灭亡', options: ['自取灭亡', '不知死活', '自寻死路', '舍身取义'], explanation: '飞蛾扑向火焰自取灭亡。', difficulty: 'medium' },
  { id: 33, front: '画蛇添足', back: '多此一举', options: ['多此一举', '节外生枝', '弄巧成拙', '锦上添花'], explanation: '蛇没有脚，画上脚反而多余。', difficulty: 'medium' },
  { id: 34, front: '亡羊补牢', back: '为时未晚', options: ['为时未晚', '亡羊得牛', '亡羊之叹', '悔之晚矣'], explanation: '丢了羊再修补羊圈，还不算太晚。', difficulty: 'medium' },
  { id: 35, front: '塞翁失马', back: '焉知非福', options: ['焉知非福', '祸福相依', '否极泰来', '因祸得福'], explanation: '边塞老人丢马谁知不是福气？坏事可能变好事。', difficulty: 'medium' },
  { id: 36, front: '螳螂捕蝉', back: '黄雀在后', options: ['黄雀在后', '不知祸临', '自食其果', '前有狼后有虎'], explanation: '螳螂捕蝉不知身后有黄雀要吃它。', difficulty: 'medium' },
  { id: 37, front: '鱼目混珠', back: '以假乱真', options: ['以假乱真', '鱼龙混杂', '假冒伪劣', '珠玉在前'], explanation: '用鱼眼睛冒充珍珠，假的混在真里面。', difficulty: 'medium' },
  { id: 38, front: '挂羊头卖狗肉', back: '有名无实', options: ['有名无实', '言行不一', '欺骗顾客', '虚有其表'], explanation: '招牌是羊肉实际卖狗肉，名不符实。', difficulty: 'medium' },
  { id: 39, front: '搬起石头砸自己的脚', back: '自作自受', options: ['自作自受', '得不偿失', '害人害己', '搬石砸脚'], explanation: '搬石头砸自己脚，自己害自己。', difficulty: 'medium' },
  { id: 40, front: '此地无银三百两', back: '不打自招', options: ['不打自招', '欲盖弥彰', '掩耳盗铃', '此地无银'], explanation: '写"此地无银"反而暴露了有银的事实。', difficulty: 'medium' },
  { id: 41, front: '掩耳盗铃', back: '自欺欺人', options: ['自欺欺人', '掩人耳目', '瞒天过海', '偷铃铛'], explanation: '捂住自己耳朵偷铃铛，骗自己以为别人听不到。', difficulty: 'medium' },
  { id: 42, front: '对牛弹琴', back: '白费功夫', options: ['白费功夫', '不入耳', '牛不懂音', '明珠暗投'], explanation: '对牛弹琴牛听不懂，白费力气。', difficulty: 'medium' },
  { id: 43, front: '刘备借荆州', back: '有借无还', options: ['有借无还', '借而不还', '一借到底', '赖账不还'], explanation: '刘备借荆州后一直不还。', difficulty: 'medium' },
  { id: 44, front: '鸡蛋壳发面', back: '没多大发头', options: ['没多大发头', '无起色', '小小发展', '薄皮大馅'], explanation: '鸡蛋壳做发面（发面馒头）发不了多大。"没多大发头"指没多大发展前途。', difficulty: 'medium' },
  { id: 45, front: '孔夫子搬家', back: '净是书', options: ['净是书', '全是输', '书搬家', '书香门第'], explanation: '"净是书"谐音"净是输"，全是输。', difficulty: 'medium' },
  { id: 46, front: '老虎屁股', back: '摸不得', options: ['摸不得', '惹不起', '碰不得', '不敢动'], explanation: '老虎屁股摸不得——惹不起。', difficulty: 'medium' },
  { id: 47, front: '铁树开花', back: '百年难遇', options: ['百年难遇', '难得一见', '千载难逢', '枯木逢春'], explanation: '铁树开花极罕见，形容很难见到的事。', difficulty: 'medium' },
  { id: 48, front: '姜太公钓鱼', back: '愿者上钩', options: ['愿者上钩', '稳坐钓鱼台', '坐等好事', '顺其自然'], explanation: '姜太公用直钩钓鱼，鱼自愿上钩。', difficulty: 'medium' },
  { id: 49, front: '小和尚念经', back: '有口无心', options: ['有口无心', '念而不懂', '鹦鹉学舌', '口是心非'], explanation: '小和尚念经只是嘴巴念，心里不理解。', difficulty: 'medium' },
  { id: 50, front: '纸老虎', back: '外强中干', options: ['外强中干', '不堪一击', '虚张声势', '纸包不住火'], explanation: '纸老虎外表吓人实际不堪一击。', difficulty: 'medium' },
  { id: 51, front: '巧妇难为无米之炊', back: '无能为力', options: ['无能为力', '有心无力', '束手无策', '巧妇难炊'], explanation: '再巧的媳妇没米也做不出饭。', difficulty: 'medium' },
  { id: 52, front: '老虎拉车', back: '没人敢赶', options: ['没人敢赶', '横冲直撞', '谁敢', '力大无穷'], explanation: '老虎拉车没人敢去赶（驾）。', difficulty: 'medium' },
  { id: 53, front: '丈二和尚', back: '摸不着头脑', options: ['摸不着头脑', '高不可攀', '糊涂僧', '不知所措'], explanation: '一丈二的和尚太高了摸不到头，形容搞不明白。', difficulty: 'medium' },
  { id: 54, front: '八仙过海', back: '各显神通', options: ['各显神通', '齐心协力', '八仙齐渡', '各有所长'], explanation: '八仙各有法术过海，各显本领。', difficulty: 'medium' },
  { id: 55, front: '和尚到了姑子庵', back: '不妙', options: ['不妙', '妙不可言', '阴阳不分', '闹翻天'], explanation: '"不妙"谐音"不庙"，和尚到尼姑庵不妙。', difficulty: 'medium' },
  { id: 56, front: '屠夫说猪，农夫说谷', back: '三句不离本行', options: ['三句不离本行', '各执一词', '行行出状元', '隔行如隔山'], explanation: '说话总是围绕自己的行业。', difficulty: 'medium' },
  { id: 57, front: '关公面前耍大刀', back: '自不量力', options: ['自不量力', '班门弄斧', '关公舞刀', '不自量力'], explanation: '在关公面前耍刀，关公就是刀法高手。', difficulty: 'medium' },
  { id: 58, front: '仇人相见', back: '分外眼红', options: ['分外眼红', '怒目相视', '恨之入骨', '咬牙切齿'], explanation: '仇人见面格外气愤眼红。', difficulty: 'medium' },
  { id: 59, front: '天上掉馅饼', back: '不可能', options: ['不可能', '好事天降', '做梦', '异想天开'], explanation: '天上不会掉馅饼，形容不可能的事。', difficulty: 'medium' },
  { id: 60, front: '班门弄斧', back: '不自量力', options: ['不自量力', '自取其辱', '鲁班门前', '不懂规矩'], explanation: '在鲁班门前耍斧头，鲁班是木匠祖师。', difficulty: 'medium' },
  { id: 61, front: '一粒老鼠屎', back: '坏了一锅粥', options: ['坏了一锅粥', '小恶大害', '一点坏全局', '星星之火'], explanation: '一粒老鼠屎毁了一整锅粥。', difficulty: 'medium' },
  { id: 62, front: '蜻蜓点水', back: '不深入', options: ['不深入', '浅尝辄止', '一触即走', '浮光掠影'], explanation: '蜻蜓点水只碰一下水面不深入。', difficulty: 'medium' },
  { id: 63, front: '刘备摔孩子', back: '收买人心', options: ['收买人心', '假仁假义', '刘备假摔', '作假戏真'], explanation: '刘备摔阿斗是为了收买赵云忠心。', difficulty: 'medium' },
  { id: 64, front: '看人挑担不吃力', back: '不知挑担难', options: ['不知挑担难', '旁观者清', '站着说话不腰疼', '隔岸观火'], explanation: '看着别人挑担觉得轻松，自己挑才知道难。', difficulty: 'medium' },
  { id: 65, front: '盐店里卖气球', back: '闲言闲语', options: ['闲言闲语', '咸言咸语', '夸夸其谈', '空话连篇'], explanation: '"闲"谐音"咸"，盐店卖气球（闲话）。', difficulty: 'medium' },

  // ===== Hard (66-100) =====
  { id: 66, front: '周瑜打黄盖', back: '一个愿打一个愿挨', options: ['一个愿打一个愿挨', '将计就计', '苦肉计', '假打真伤'], explanation: '周瑜和黄盖用苦肉计，一个愿打一个愿挨。', difficulty: 'hard' },
  { id: 67, front: '徐庶进曹营', back: '一言不发', options: ['一言不发', '有话不说', '沉默是金', '闭口不言'], explanation: '徐庶被迫进曹营但不为曹操献一计。', difficulty: 'hard' },
  { id: 68, front: '张飞穿针', back: '大眼瞪小眼', options: ['大眼瞪小眼', '粗中有细', '张飞绣花', '有勇无谋'], explanation: '张飞大眼睛穿小针孔，大眼瞪小眼。', difficulty: 'hard' },
  { id: 69, front: '刘备的江山', back: '哭出来的', options: ['哭出来的', '借来的江山', '三顾茅庐', '桃园结义'], explanation: '刘备靠哭打动人心获得支持夺取江山。', difficulty: 'hard' },
  { id: 70, front: '张飞卖刺猬', back: '人强货扎手', options: ['人强货扎手', '有勇无谋', '刺猬难卖', '强人卖棘货'], explanation: '张飞凶猛刺猬又扎手，人厉害货也扎手。', difficulty: 'hard' },
  { id: 71, front: '关公赴会', back: '单刀直入', options: ['单刀直入', '英勇无畏', '单刀赴会', '大义凛然'], explanation: '关公带一把刀赴鲁肃之约，单刀直入。', difficulty: 'hard' },
  { id: 72, front: '鲁肃讨荆州', back: '空手而归', options: ['空手而归', '一无所获', '无功而返', '白跑一趟'], explanation: '鲁肃多次讨荆州都讨不到。', difficulty: 'hard' },
  { id: 73, front: '许褚战马超', back: '赤膊上阵', options: ['赤膊上阵', '勇猛无比', '裸衣决斗', '拼命一战'], explanation: '许褚脱衣赤膊战马超。', difficulty: 'hard' },
  { id: 74, front: '刘备借荆州', back: '一借永不还', options: ['一借永不还', '赖账高手', '借而不还', '据为己有'], explanation: '刘备借荆州后一直占有不归还。', difficulty: 'hard' },
  { id: 75, front: '曹操吃鸡肋', back: '食之无味弃之可惜', options: ['食之无味弃之可惜', '鸡肋难舍', '进退两难', '举棋不定'], explanation: '鸡肋吃着没味道丢了可惜，形容两难。', difficulty: 'hard' },
  { id: 76, front: '司马炎篡魏', back: '名正言不顺', options: ['名正言不顺', '篡位夺权', '以下犯上', '强取豪夺'], explanation: '司马炎篡魏名不正言不顺。', difficulty: 'hard' },
  { id: 77, front: '孙权杀关羽', back: '嫁祸于人', options: ['嫁祸于人', '借刀杀人', '杀鸡儆猴', '斩草除根'], explanation: '孙权杀关羽把首级送给曹操嫁祸。', difficulty: 'hard' },
  { id: 78, front: '吕布戏貂蝉', back: '上当受骗', options: ['上当受骗', '美人计', '英雄难过美人关', '色迷心窍'], explanation: '吕布被貂蝉迷惑中了王允美人计。', difficulty: 'hard' },
  { id: 79, front: '赵云大战长坂坡', back: '大显神威', options: ['大显神威', '七进七出', '单骑救主', '英勇无敌'], explanation: '赵云在长坂坡七进七出救阿斗显神威。', difficulty: 'hard' },
  { id: 80, front: '草船借箭', back: '满载而归', options: ['满载而归', '巧用天时', '借箭有方', '诸葛亮妙计'], explanation: '诸葛亮草船借箭从曹营满载箭矢回来。', difficulty: 'hard' },
  { id: 81, front: '斩草不除根', back: '春风吹又生', options: ['春风吹又生', '后患无穷', '根深蒂固', '草长莺飞'], explanation: '斩草不除根，春风一吹又会长出来。', difficulty: 'hard' },
  { id: 82, front: '木匠戴枷', back: '自作自受', options: ['自作自受', '自找苦吃', '自食其果', '搬石砸脚'], explanation: '木匠自己做的枷锁戴在自己头上。', difficulty: 'hard' },
  { id: 83, front: '程咬金上阵', back: '就那三板斧', options: ['就那三板斧', '三板斧就没了', '力气大没谋', '勇而无谋'], explanation: '程咬金只会三板斧，本事有限。', difficulty: 'hard' },
  { id: 84, front: '张飞抓耗子', back: '大眼瞪小眼', options: ['大眼瞪小眼', '粗人做细事', '张飞抓鼠', '力不从心'], explanation: '张飞大眼瞪小老鼠，形容互相对望。', difficulty: 'hard' },
  { id: 85, front: '张飞吃豆芽', back: '小菜一碟', options: ['小菜一碟', '大口小菜', '小菜不难', '轻而易举'], explanation: '对张飞来说吃豆芽太容易了——小菜一碟。', difficulty: 'hard' },
  { id: 86, front: '关帝庙求子', back: '踏错了门', options: ['踏错了门', '走错庙了', '求错神了', '拜错佛'], explanation: '关帝庙是拜关公的，不是求子的地方。', difficulty: 'hard' },
  { id: 87, front: '梁山好汉', back: '逼上梁山', options: ['逼上梁山', '一百单八将', '替天行道', '豪杰聚会'], explanation: '梁山好汉都是被逼无奈才上梁山的。', difficulty: 'hard' },
  { id: 88, front: '唐僧念经', back: '一本正经', options: ['一本正经', '天天念', '唠叨不休', '口不停经'], explanation: '唐僧念经一本正经（认真）。', difficulty: 'hard' },
  { id: 89, front: '孙悟空大闹天宫', back: '翻了天', options: ['翻了天', '翻天覆地', '大闹不休', '搅得天翻'], explanation: '孙悟空闹得天宫翻天。', difficulty: 'hard' },
  { id: 90, front: '猪八戒吃人参果', back: '全不知滋味', options: ['全不知滋味', '囫囵吞枣', '不知好歹', '猴急猴急'], explanation: '猪八戒囫囵吞下人参果，没品出味道。', difficulty: 'hard' },
  { id: 91, front: '张飞扔鸡毛', back: '有劲难使', options: ['有劲难使', '力不从心', '有力无处用', '无用武之地'], explanation: '张飞力气大但扔鸡毛使不上劲。', difficulty: 'hard' },
  { id: 92, front: '曹操遇蒋干', back: '倒霉到家', options: ['倒霉到家', '误听小人', '上当受骗', '遇人不淑'], explanation: '曹操遇蒋干被骗倒霉到了极点。', difficulty: 'hard' },
  { id: 93, front: '诸葛亮挥泪斩马谡', back: '顾全大局', options: ['顾全大局', '执法如山', '大义灭亲', '忍痛割爱'], explanation: '诸葛亮为军法斩马谡顾全大局。', difficulty: 'hard' },
  { id: 94, front: '包公断案', back: '铁面无私', options: ['铁面无私', '公正严明', '六亲不认', '明察秋毫'], explanation: '包公断案公正不偏私。', difficulty: 'hard' },
  { id: 95, front: '韩信将兵', back: '多多益善', options: ['多多益善', '多多益办', '兵多势大', '人多好办事'], explanation: '韩信说自己带兵越多越好。', difficulty: 'hard' },
  { id: 96, front: '项庄舞剑', back: '意在沛公', options: ['意在沛公', '别有用心', '暗藏杀机', '醉翁之意不在酒'], explanation: '项庄舞剑名义助酒实际想杀刘邦。', difficulty: 'hard' },
  { id: 97, front: '楚霸王举鼎', back: '力大无穷', options: ['力大无穷', '力拔山兮', '大勇无谋', '勇猛无双'], explanation: '项羽力大能举铜鼎。', difficulty: 'hard' },
  { id: 98, front: '秦叔宝卖马', back: '穷途末路', options: ['穷途末路', '英雄落难', '英雄卖马', '困窘不堪'], explanation: '秦叔宝穷困潦倒被迫卖马。', difficulty: 'hard' },
  { id: 99, front: '曹操转胎', back: '疑心重', options: ['疑心重', '多疑多虑', '奸雄本性', '生性多疑'], explanation: '曹操生性多疑。', difficulty: 'hard' },
  { id: 100, front: '孙二娘开店', back: '谋财害命', options: ['谋财害命', '黑店害人', '心狠手辣', '不义之财'], explanation: '孙二娘开黑店图财害命。', difficulty: 'hard' },
]

export default DATA