import type { Poem } from './types'

const POEMS: Poem[] = [
  // ===== Easy (1-30) — 唐诗名篇 / 宋词经典 =====
  { id: 1, upper: '床前明月光', lower: '疑是地上霜', title: '静夜思', author: '李白', dynasty: '唐', options: ['举头望明月', '低头思故乡', '疑是地上霜', '对影成三人'], difficulty: 'easy' },
  { id: 2, upper: '春眠不觉晓', lower: '处处闻啼鸟', title: '春晓', author: '孟浩然', dynasty: '唐', options: ['夜来风雨声', '春草明年绿', '处处闻啼鸟', '花落知多少'], difficulty: 'easy' },
  { id: 3, upper: '白日依山尽', lower: '黄河入海流', title: '登鹳雀楼', author: '王之涣', dynasty: '唐', options: ['欲穷千里目', '更上一层楼', '黄河入海流', '春风不度玉门关'], difficulty: 'easy' },
  { id: 4, upper: '锄禾日当午', lower: '汗滴禾下土', title: '悯农', author: '李绅', dynasty: '唐', options: ['粒粒皆辛苦', '春种一粒粟', '汗滴禾下土', '谁知盘中餐'], difficulty: 'easy' },
  { id: 5, upper: '离离原上草', lower: '一岁一枯荣', title: '赋得古原草送别', author: '白居易', dynasty: '唐', options: ['一岁一枯荣', '野火烧不尽', '春风吹又生', '远芳侵古道'], difficulty: 'easy' },
  { id: 6, upper: '日照香炉生紫烟', lower: '遥看瀑布挂前川', title: '望庐山瀑布', author: '李白', dynasty: '唐', options: ['疑是银河落九天', '孤帆远影碧空尽', '遥看瀑布挂前川', '飞流直下三千尺'], difficulty: 'easy' },
  { id: 7, upper: '千山鸟飞绝', lower: '万径人踪灭', title: '江雪', author: '柳宗元', dynasty: '唐', options: ['孤舟蓑笠翁', '万径人踪灭', '独钓寒江雪', '白云千载空悠悠'], difficulty: 'easy' },
  { id: 8, upper: '两个黄鹂鸣翠柳', lower: '一行白鹭上青天', title: '绝句', author: '杜甫', dynasty: '唐', options: ['门泊东吴万里船', '窗含西岭千秋雪', '一行白鹭上青天', '泥融飞燕子'], difficulty: 'easy' },
  { id: 9, upper: '独在异乡为异客', lower: '每逢佳节倍思亲', title: '九月九日忆山东兄弟', author: '王维', dynasty: '唐', options: ['遍插茱萸少一人', '每逢佳节倍思亲', '遥知兄弟登高处', '西出阳关无故人'], difficulty: 'easy' },
  { id: 10, upper: '好雨知时节', lower: '当春乃发生', title: '春夜喜雨', author: '杜甫', dynasty: '唐', options: ['润物细无声', '当春乃发生', '花重锦官城', '随风潜入夜'], difficulty: 'easy' },
  { id: 11, upper: '月落乌啼霜满天', lower: '江枫渔火对愁眠', title: '枫桥夜泊', author: '张继', dynasty: '唐', options: ['霜叶红于二月花', '江枫渔火对愁眠', '夜半钟声到客船', '姑苏城外寒山寺'], difficulty: 'easy' },
  { id: 12, upper: '秦时明月汉时关', lower: '万里长征人未还', title: '出塞', author: '王昌龄', dynasty: '唐', options: ['春风不度玉门关', '万里长征人未还', '不教胡马度阴山', '但使龙城飞将在'], difficulty: 'easy' },
  { id: 13, upper: '慈母手中线', lower: '游子身上衣', title: '游子吟', author: '孟郊', dynasty: '唐', options: ['谁言寸草心', '游子身上衣', '临行密密缝', '意恐迟迟归'], difficulty: 'easy' },
  { id: 14, upper: '朝辞白帝彩云间', lower: '千里江陵一日还', title: '早发白帝城', author: '李白', dynasty: '唐', options: ['孤帆远影碧空尽', '两岸猿声啼不住', '轻舟已过万重山', '千里江陵一日还'], difficulty: 'easy' },
  { id: 15, upper: '葡萄美酒夜光杯', lower: '欲饮琵琶马上催', title: '凉州词', author: '王翰', dynasty: '唐', options: ['醉卧沙场君莫笑', '春风不度玉门关', '古来征战几人回', '欲饮琵琶马上催'], difficulty: 'easy' },
  { id: 16, upper: '大漠孤烟直', lower: '长河落日圆', title: '使至塞上', author: '王维', dynasty: '唐', options: ['长河落日圆', '都护在燕然', '萧关逢候骑', '明月出天山'], difficulty: 'easy' },
  { id: 17, upper: '清明时节雨纷纷', lower: '路上行人欲断魂', title: '清明', author: '杜牧', dynasty: '唐', options: ['路上行人欲断魂', '牧童遥指杏花村', '借问酒家何处有', '停车坐爱枫林晚'], difficulty: 'easy' },
  { id: 18, upper: '红豆生南国', lower: '春来发几枝', title: '相思', author: '王维', dynasty: '唐', options: ['此物最相思', '愿君多采撷', '春来发几枝', '劝君更尽一杯酒'], difficulty: 'easy' },
  { id: 19, upper: '松下问童子', lower: '言师采药去', title: '寻隐者不遇', author: '贾岛', dynasty: '唐', options: ['只在此山中', '松下问童子', '云深不知处', '言师采药去'], difficulty: 'easy' },
  { id: 20, upper: '黄河远上白云间', lower: '一片孤城万仞山', title: '凉州词', author: '王之涣', dynasty: '唐', options: ['一片孤城万仞山', '春风不度玉门关', '葡萄美酒夜光杯', '羌笛何须怨杨柳'], difficulty: 'easy' },
  { id: 21, upper: '相见时难别亦难', lower: '东风无力百花残', title: '无题', author: '李商隐', dynasty: '唐', options: ['东风无力百花残', '蜡炬成灰泪始干', '春蚕到死丝方尽', '青鸟殷勤为探看'], difficulty: 'easy' },
  { id: 22, upper: '渭城朝雨浥轻尘', lower: '客舍青青柳色新', title: '送元二使安西', author: '王维', dynasty: '唐', options: ['每逢佳节倍思亲', '西出阳关无故人', '客舍青青柳色新', '劝君更尽一杯酒'], difficulty: 'easy' },
  { id: 23, upper: '远上寒山石径斜', lower: '白云生处有人家', title: '山行', author: '杜牧', dynasty: '唐', options: ['白云生处有人家', '停车坐爱枫林晚', '霜叶红于二月花', '水村山郭酒旗风'], difficulty: 'easy' },
  { id: 24, upper: '蓬头稚子学垂纶', lower: '侧坐莓苔草映身', title: '小儿垂钓', author: '胡令能', dynasty: '唐', options: ['路人借问遥招手', '松下问童子', '怕得鱼惊不应人', '侧坐莓苔草映身'], difficulty: 'easy' },
  { id: 25, upper: '少小离家老大回', lower: '乡音无改鬓毛衰', title: '回乡偶书', author: '贺知章', dynasty: '唐', options: ['笑问客从何处来', '儿童相见不相识', '乡音无改鬓毛衰', '二月春风似剪刀'], difficulty: 'easy' },
  { id: 26, upper: '碧玉妆成一树高', lower: '万条垂下绿丝绦', title: '咏柳', author: '贺知章', dynasty: '唐', options: ['不知细叶谁裁出', '春风吹又生', '万条垂下绿丝绦', '二月春风似剪刀'], difficulty: 'easy' },
  { id: 27, upper: '鹅鹅鹅', lower: '曲项向天歌', title: '咏鹅', author: '骆宾王', dynasty: '唐', options: ['曲项向天歌', '春眠不觉晓', '红掌拨清波', '白毛浮绿水'], difficulty: 'easy' },
  { id: 28, upper: '向晚意不适', lower: '驱车登古原', title: '登乐游原', author: '李商隐', dynasty: '唐', options: ['夕阳无限好', '向晚意不适', '只是近黄昏', '驱车登古原'], difficulty: 'easy' },
  { id: 29, upper: '横看成岭侧成峰', lower: '远近高低各不同', title: '题西林壁', author: '苏轼', dynasty: '宋', options: ['不识庐山真面目', '飞流直下三千尺', '只缘身在此山中', '远近高低各不同'], difficulty: 'easy' },
  { id: 30, upper: '但愿人长久', lower: '千里共婵娟', title: '水调歌头', author: '苏轼', dynasty: '宋', options: ['千里共婵娟', '高处不胜寒', '把酒问青天', '明月几时有'], difficulty: 'easy' },

  // ===== Medium (31-65) =====
  { id: 31, upper: '海内存知己', lower: '天涯若比邻', title: '送杜少府之任蜀州', author: '王勃', dynasty: '唐', options: ['儿女共沾巾', '天涯若比邻', '无为在歧路', '同是天涯沦落人'], difficulty: 'medium' },
  { id: 32, upper: '随风潜入夜', lower: '润物细无声', title: '春夜喜雨', author: '杜甫', dynasty: '唐', options: ['润物细无声', '江船火独明', '野径云俱黑', '花重锦官城'], difficulty: 'medium' },
  { id: 33, upper: '两岸猿声啼不住', lower: '轻舟已过万重山', title: '早发白帝城', author: '李白', dynasty: '唐', options: ['轻舟已过万重山', '千里江陵一日还', '飞流直下三千尺', '孤帆远影碧空尽'], difficulty: 'medium' },
  { id: 34, upper: '春蚕到死丝方尽', lower: '蜡炬成灰泪始干', title: '无题', author: '李商隐', dynasty: '唐', options: ['青鸟殷勤为探看', '蜡炬成灰泪始干', '东风无力百花残', '蓬山此去无多路'], difficulty: 'medium' },
  { id: 35, upper: '劝君更尽一杯酒', lower: '西出阳关无故人', title: '送元二使安西', author: '王维', dynasty: '唐', options: ['西出阳关无故人', '每逢佳节倍思亲', '渭城朝雨浥轻尘', '客舍青青柳色新'], difficulty: 'medium' },
  { id: 36, upper: '停车坐爱枫林晚', lower: '霜叶红于二月花', title: '山行', author: '杜牧', dynasty: '唐', options: ['远上寒山石径斜', '霜叶红于二月花', '白云生处有人家', '水村山郭酒旗风'], difficulty: 'medium' },
  { id: 37, upper: '野火烧不尽', lower: '春风吹又生', title: '赋得古原草送别', author: '白居易', dynasty: '唐', options: ['远芳侵古道', '晴翠接荒城', '春风吹又生', '一岁一枯荣'], difficulty: 'medium' },
  { id: 38, upper: '欲穷千里目', lower: '更上一层楼', title: '登鹳雀楼', author: '王之涣', dynasty: '唐', options: ['黄河入海流', '春风不度玉门关', '白日依山尽', '更上一层楼'], difficulty: 'medium' },
  { id: 39, upper: '谁言寸草心', lower: '报得三春晖', title: '游子吟', author: '孟郊', dynasty: '唐', options: ['临行密密缝', '游子身上衣', '报得三春晖', '意恐迟迟归'], difficulty: 'medium' },
  { id: 40, upper: '飞流直下三千尺', lower: '疑是银河落九天', title: '望庐山瀑布', author: '李白', dynasty: '唐', options: ['遥看瀑布挂前川', '孤帆远影碧空尽', '日照香炉生紫烟', '疑是银河落九天'], difficulty: 'medium' },
  { id: 41, upper: '不识庐山真面目', lower: '只缘身在此山中', title: '题西林壁', author: '苏轼', dynasty: '宋', options: ['只缘身在此山中', '飞流直下三千尺', '远近高低各不同', '横看成岭侧成峰'], difficulty: 'medium' },
  { id: 42, upper: '夕阳无限好', lower: '只是近黄昏', title: '登乐游原', author: '李商隐', dynasty: '唐', options: ['夕阳无限好', '驱车登古原', '只是近黄昏', '向晚意不适'], difficulty: 'medium' },
  { id: 43, upper: '醉卧沙场君莫笑', lower: '古来征战几人回', title: '凉州词', author: '王翰', dynasty: '唐', options: ['欲饮琵琶马上催', '春风不度玉门关', '葡萄美酒夜光杯', '古来征战几人回'], difficulty: 'medium' },
  { id: 44, upper: '借问酒家何处有', lower: '牧童遥指杏花村', title: '清明', author: '杜牧', dynasty: '唐', options: ['路上行人欲断魂', '牧童遥指杏花村', '停车坐爱枫林晚', '清明时节雨纷纷'], difficulty: 'medium' },
  { id: 45, upper: '遥知兄弟登高处', lower: '遍插茱萸少一人', title: '九月九日忆山东兄弟', author: '王维', dynasty: '唐', options: ['西出阳关无故人', '遍插茱萸少一人', '独在异乡为异客', '每逢佳节倍思亲'], difficulty: 'medium' },
  { id: 46, upper: '姑苏城外寒山寺', lower: '夜半钟声到客船', title: '枫桥夜泊', author: '张继', dynasty: '唐', options: ['月落乌啼霜满天', '江枫渔火对愁眠', '霜叶红于二月花', '夜半钟声到客船'], difficulty: 'medium' },
  { id: 47, upper: '但使龙城飞将在', lower: '不教胡马度阴山', title: '出塞', author: '王昌龄', dynasty: '唐', options: ['万里长征人未还', '春风不度玉门关', '不教胡马度阴山', '秦时明月汉时关'], difficulty: 'medium' },
  { id: 48, upper: '不知细叶谁裁出', lower: '二月春风似剪刀', title: '咏柳', author: '贺知章', dynasty: '唐', options: ['春风吹又生', '万条垂下绿丝绦', '碧玉妆成一树高', '二月春风似剪刀'], difficulty: 'medium' },
  { id: 49, upper: '儿童相见不相识', lower: '笑问客从何处来', title: '回乡偶书', author: '贺知章', dynasty: '唐', options: ['少小离家老大回', '笑问客从何处来', '乡音无改鬓毛衰', '每逢佳节倍思亲'], difficulty: 'medium' },
  { id: 50, upper: '愿君多采撷', lower: '此物最相思', title: '相思', author: '王维', dynasty: '唐', options: ['春来发几枝', '此物最相思', '劝君更尽一杯酒', '红豆生南国'], difficulty: 'medium' },
  { id: 51, upper: '只在此山中', lower: '云深不知处', title: '寻隐者不遇', author: '贾岛', dynasty: '唐', options: ['远上寒山石径斜', '言师采药去', '松下问童子', '云深不知处'], difficulty: 'medium' },
  { id: 52, upper: '羌笛何须怨杨柳', lower: '春风不度玉门关', title: '凉州词', author: '王之涣', dynasty: '唐', options: ['一片孤城万仞山', '春风不度玉门关', '葡萄美酒夜光杯', '黄河远上白云间'], difficulty: 'medium' },
  { id: 53, upper: '莫愁前路无知己', lower: '天下谁人不识君', title: '别董大', author: '高适', dynasty: '唐', options: ['海内存知己', '天下谁人不识君', '北风吹雁雪纷纷', '千里黄云白日曛'], difficulty: 'medium' },
  { id: 54, upper: '忽如一夜春风来', lower: '千树万树梨花开', title: '白雪歌送武判官归京', author: '岑参', dynasty: '唐', options: ['千树万树梨花开', '胡天八月即飞雪', '北风卷地白草折', '散入珠帘湿罗幕'], difficulty: 'medium' },
  { id: 55, upper: '欲将轻骑逐', lower: '大雪满弓刀', title: '塞下曲', author: '卢纶', dynasty: '唐', options: ['单于夜遁逃', '大雪满弓刀', '月黑雁飞高', '欲将轻骑逐'], difficulty: 'medium' },
  { id: 56, upper: '窗含西岭千秋雪', lower: '门泊东吴万里船', title: '绝句', author: '杜甫', dynasty: '唐', options: ['一行白鹭上青天', '门泊东吴万里船', '两个黄鹂鸣翠柳', '泥融飞燕子'], difficulty: 'medium' },
  { id: 57, upper: '谁知盘中餐', lower: '粒粒皆辛苦', title: '悯农', author: '李绅', dynasty: '唐', options: ['锄禾日当午', '粒粒皆辛苦', '春种一粒粟', '汗滴禾下土'], difficulty: 'medium' },
  { id: 58, upper: '路人借问遥招手', lower: '怕得鱼惊不应人', title: '小儿垂钓', author: '胡令能', dynasty: '唐', options: ['蓬头稚子学垂纶', '松下问童子', '怕得鱼惊不应人', '侧坐莓苔草映身'], difficulty: 'medium' },
  { id: 59, upper: '黑云翻墨未遮山', lower: '白雨跳珠乱入船', title: '六月二十七日望湖楼醉书', author: '苏轼', dynasty: '宋', options: ['白雨跳珠乱入船', '卷地风来忽吹散', '望湖楼下水如天', '黑云翻墨未遮山'], difficulty: 'medium' },
  { id: 60, upper: '生当作人杰', lower: '死亦为鬼雄', title: '夏日绝句', author: '李清照', dynasty: '宋', options: ['至今思项羽', '生当作人杰', '不肯过江东', '死亦为鬼雄'], difficulty: 'medium' },
  { id: 61, upper: '采菊东篱下', lower: '悠然见南山', title: '饮酒', author: '陶渊明', dynasty: '东晋', options: ['山气日夕佳', '飞鸟相与还', '悠然见南山', '此中有真意'], difficulty: 'medium' },
  { id: 62, upper: '问渠那得清如许', lower: '为有源头活水来', title: '观书有感', author: '朱熹', dynasty: '宋', options: ['天光云影共徘徊', '不识庐山真面目', '半亩方塘一鉴开', '为有源头活水来'], difficulty: 'medium' },
  { id: 63, upper: '竹外桃花三两枝', lower: '春江水暖鸭先知', title: '惠崇春江晚景', author: '苏轼', dynasty: '宋', options: ['正是河豚欲上时', '两个黄鹂鸣翠柳', '春江水暖鸭先知', '蒌蒿满地芦芽短'], difficulty: 'medium' },
  { id: 64, upper: '等闲识得东风面', lower: '万紫千红总是春', title: '春日', author: '朱熹', dynasty: '宋', options: ['不知细叶谁裁出', '胜日寻芳泗水滨', '万紫千红总是春', '无边光景一时新'], difficulty: 'medium' },
  { id: 65, upper: '粉身碎骨浑不怕', lower: '要留清白在人间', title: '石灰吟', author: '于谦', dynasty: '明', options: ['粉身碎骨浑不怕', '烈火焚烧若等闲', '千锤万凿出深山', '要留清白在人间'], difficulty: 'medium' },

  // ===== Hard (66-100) =====
  { id: 66, upper: '落霞与孤鹜齐飞', lower: '秋水共长天一色', title: '滕王阁序', author: '王勃', dynasty: '唐', options: ['雁阵惊寒声断衡阳之浦', '渔舟唱晚响穷彭蠡之滨', '大漠孤烟直', '秋水共长天一色'], difficulty: 'hard' },
  { id: 67, upper: '会挽雕弓如满月', lower: '西北望射天狼', title: '江城子·密州出猎', author: '苏轼', dynasty: '宋', options: ['左牵黄右擎苍', '老夫聊发少年狂', '西北望射天狼', '锦帽貂裘千骑卷平冈'], difficulty: 'hard' },
  { id: 68, upper: '安能摧眉折腰事权贵', lower: '使我不得开心颜', title: '梦游天姥吟留别', author: '李白', dynasty: '唐', options: ['世间行乐亦如此', '使我不得开心颜', '且放白鹿青崖间', '古来万事东流水'], difficulty: 'hard' },
  { id: 69, upper: '出师未捷身先死', lower: '长使英雄泪满襟', title: '蜀相', author: '杜甫', dynasty: '唐', options: ['出师未捷身先死', '两朝开济老臣心', '三顾频烦天下计', '长使英雄泪满襟'], difficulty: 'hard' },
  { id: 70, upper: '三顾频烦天下计', lower: '两朝开济老臣心', title: '蜀相', author: '杜甫', dynasty: '唐', options: ['长使英雄泪满襟', '两朝开济老臣心', '丞相祠堂何处寻', '出师未捷身先死'], difficulty: 'hard' },
  { id: 71, upper: '曾经沧海难为水', lower: '除却巫山不是云', title: '离思', author: '元稹', dynasty: '唐', options: ['除却巫山不是云', '取次花丛懒回顾', '春风不度玉门关', '半缘修道半缘君'], difficulty: 'hard' },
  { id: 72, upper: '风萧萧兮易水寒', lower: '壮士一去兮不复还', title: '易水歌', author: '荆轲', dynasty: '先秦', options: ['风萧萧兮易水寒', '大漠孤烟直', '出师未捷身先死', '壮士一去兮不复还'], difficulty: 'hard' },
  { id: 73, upper: '大江东去浪淘尽', lower: '千古风流人物', title: '念奴娇·赤壁怀古', author: '苏轼', dynasty: '宋', options: ['乱石穿空惊涛拍岸', '故垒西边人道是三国周郎赤壁', '江山如画一时多少豪杰', '千古风流人物'], difficulty: 'hard' },
  { id: 74, upper: '寻寻觅觅冷冷清清', lower: '凄凄惨惨戚戚', title: '声声慢', author: '李清照', dynasty: '宋', options: ['乍暖还寒时候最难将息', '满地黄花堆积', '凄凄惨惨戚戚', '三杯两盏淡酒怎敌他晚来风急'], difficulty: 'hard' },
  { id: 75, upper: '身无彩凤双飞翼', lower: '心有灵犀一点通', title: '无题', author: '李商隐', dynasty: '唐', options: ['相见时难别亦难', '分曹射覆蜡灯红', '隔座送钩春酒暖', '心有灵犀一点通'], difficulty: 'hard' },
  { id: 76, upper: '同是天涯沦落人', lower: '相逢何必曾相识', title: '琵琶行', author: '白居易', dynasty: '唐', options: ['相逢何必曾相识', '海内存知己', '莫愁前路无知己', '天涯若比邻'], difficulty: 'hard' },
  { id: 77, upper: '欲渡黄河冰塞川', lower: '将登太行雪满山', title: '行路难', author: '李白', dynasty: '唐', options: ['行路难行路难多歧路今安在', '将登太行雪满山', '忽复乘舟梦日边', '闲来垂钓碧溪上'], difficulty: 'hard' },
  { id: 78, upper: '别有幽愁暗恨生', lower: '此时无声胜有声', title: '琵琶行', author: '白居易', dynasty: '唐', options: ['银瓶乍破水浆迸', '此时无声胜有声', '铁骑突出刀枪鸣', '同是天涯沦落人'], difficulty: 'hard' },
  { id: 79, upper: '长风破浪会有时', lower: '直挂云帆济沧海', title: '行路难', author: '李白', dynasty: '唐', options: ['直挂云帆济沧海', '闲来垂钓碧溪上', '将登太行雪满山', '欲渡黄河冰塞川'], difficulty: 'hard' },
  { id: 80, upper: '晓看红湿处', lower: '花重锦官城', title: '春夜喜雨', author: '杜甫', dynasty: '唐', options: ['花重锦官城', '野径云俱黑', '润物细无声', '随风潜入夜'], difficulty: 'hard' },
  { id: 81, upper: '黑云压城城欲摧', lower: '甲光向日金鳞开', title: '雁门太守行', author: '李贺', dynasty: '唐', options: ['报君黄金台上意', '角声满天秋色里', '甲光向日金鳞开', '塞上燕脂凝夜紫'], difficulty: 'hard' },
  { id: 82, upper: '年年岁岁花相似', lower: '岁岁年年人不同', title: '代悲白头翁', author: '刘希夷', dynasty: '唐', options: ['年年岁岁花相似', '岁岁年年人不同', '寄言全盛红颜子', '须怜半死白头翁'], difficulty: 'hard' },
  { id: 83, upper: '枝上柳绵吹又少', lower: '天涯何处无芳草', title: '蝶恋花', author: '苏轼', dynasty: '宋', options: ['花褪残红青杏小', '枝上柳绵吹又少', '天涯何处无芳草', '燕子飞时绿水人家绕'], difficulty: 'hard' },
  { id: 84, upper: '草长莺飞二月天', lower: '拂堤杨柳醉春烟', title: '村居', author: '高鼎', dynasty: '清', options: ['拂堤杨柳醉春烟', '忙趁东风放纸鸢', '儿童散学归来早', '草长莺飞二月天'], difficulty: 'hard' },
  { id: 85, upper: '人生自古谁无死', lower: '留取丹心照汗青', title: '过零丁洋', author: '文天祥', dynasty: '宋', options: ['留取丹心照汗青', '山河破碎风飘絮', '辛苦遭逢起一经', '人生自古谁无死'], difficulty: 'hard' },
  { id: 86, upper: '谁家玉笛暗飞声', lower: '散入春风满洛城', title: '春夜洛城闻笛', author: '李白', dynasty: '唐', options: ['此夜曲中闻折柳', '谁家玉笛暗飞声', '散入春风满洛城', '何人不起故园情'], difficulty: 'hard' },
  { id: 87, upper: '山外青山楼外楼', lower: '西湖歌舞几时休', title: '题临安邸', author: '林升', dynasty: '宋', options: ['西湖歌舞几时休', '直把杭州作汴州', '山外青山楼外楼', '暖风熏得游人醉'], difficulty: 'hard' },
  { id: 88, upper: '此中有真意', lower: '欲辨已忘言', title: '饮酒', author: '陶渊明', dynasty: '东晋', options: ['悠然见南山', '飞鸟相与还', '欲辨已忘言', '此中有真意'], difficulty: 'hard' },
  { id: 89, upper: '寄语洛城风日道', lower: '明年春色倍还人', title: '春日京中有怀', author: '杜审言', dynasty: '唐', options: ['寄语洛城风日道', '万紫千红总是春', '今年春色倍还人', '明年春色倍还人'], difficulty: 'hard' },
  { id: 90, upper: '卷地风来忽吹散', lower: '望湖楼下水如天', title: '六月二十七日望湖楼醉书', author: '苏轼', dynasty: '宋', options: ['卷地风来忽吹散', '白雨跳珠乱入船', '黑云翻墨未遮山', '望湖楼下水如天'], difficulty: 'hard' },
  { id: 91, upper: '何当共剪西窗烛', lower: '却话巴山夜雨时', title: '夜雨寄北', author: '李商隐', dynasty: '唐', options: ['巴山楚水凄凉地', '君问归期未有期', '何当共剪西窗烛', '却话巴山夜雨时'], difficulty: 'hard' },
  { id: 92, upper: '两情若是久长时', lower: '又岂在朝朝暮暮', title: '鹊桥仙', author: '秦观', dynasty: '宋', options: ['银汉迢迢暗度', '金风玉露一相逢', '纤云弄巧飞星传恨', '又岂在朝朝暮暮'], difficulty: 'hard' },
  { id: 93, upper: '夜来风雨声', lower: '花落知多少', title: '春晓', author: '孟浩然', dynasty: '唐', options: ['春草明年绿', '处处闻啼鸟', '花落知多少', '春眠不觉晓'], difficulty: 'hard' },
  { id: 94, upper: '前不见古人', lower: '后不见来者', title: '登幽州台歌', author: '陈子昂', dynasty: '唐', options: ['独怆然而涕下', '前不见古人', '后不见来者', '念天地之悠悠'], difficulty: 'hard' },
  { id: 95, upper: '江流石不转', lower: '遗恨失吞吴', title: '八阵图', author: '杜甫', dynasty: '唐', options: ['遗恨失吞吴', '江流石不转', '名成八阵图', '功盖三分国'], difficulty: 'hard' },
  { id: 96, upper: '浩荡离愁白日斜', lower: '吟鞭东指即天涯', title: '己亥杂诗', author: '龚自珍', dynasty: '清', options: ['落红不是无情物', '浩荡离愁白日斜', '化作春泥更护花', '吟鞭东指即天涯'], difficulty: 'hard' },
  { id: 97, upper: '落红不是无情物', lower: '化作春泥更护花', title: '己亥杂诗', author: '龚自珍', dynasty: '清', options: ['粉身碎骨浑不怕', '浩荡离愁白日斜', '化作春泥更护花', '吟鞭东指即天涯'], difficulty: 'hard' },
  { id: 98, upper: '至今思项羽', lower: '不肯过江东', title: '夏日绝句', author: '李清照', dynasty: '宋', options: ['生当作人杰', '不肯过江东', '死亦为鬼雄', '至今思项羽'], difficulty: 'hard' },
  { id: 99, upper: '蒌蒿满地芦芽短', lower: '正是河豚欲上时', title: '惠崇春江晚景', author: '苏轼', dynasty: '宋', options: ['竹外桃花三两枝', '春江水暖鸭先知', '蒌蒿满地芦芽短', '正是河豚欲上时'], difficulty: 'hard' },
  { id: 100, upper: '暖风熏得游人醉', lower: '直把杭州作汴州', title: '题临安邸', author: '林升', dynasty: '宋', options: ['西湖歌舞几时休', '直把杭州作汴州', '山外青山楼外楼', '暖风熏得游人醉'], difficulty: 'hard' },
]

export default POEMS