import type { TrickRiddle } from './types'

const RIDDLES: TrickRiddle[] = [
  // ===== Easy (1-30) =====
  { id: 1, question: '什么东西越洗越脏？', answer: '水', options: ['水', '衣服', '手', '碗', '毛巾', '锅'], explanation: '洗东西的水会越来越脏。', difficulty: 'easy' },
  { id: 2, question: '什么东西你有，别人也有，但别人用的比你多？', answer: '名字', options: ['时间', '钱', '名字', '手机', '房子', '车子'], explanation: '你的名字别人叫得多，你自己很少叫。', difficulty: 'easy' },
  { id: 3, question: '什么东西天气越热它爬得越高？', answer: '温度计', options: ['蚂蚁', '气球', '蛇', '温度计', '猴子', '风筝'], explanation: '温度计里液体随温度升高而上升。', difficulty: 'easy' },
  { id: 4, question: '什么动物最容易被贴在墙上？', answer: '海豹', options: ['海豹', '苍蝇', '蝴蝶', '蜘蛛', '蜻蜓', '壁虎'], explanation: '"海豹"谐音"海报"，海报可以贴墙上。', difficulty: 'easy' },
  { id: 5, question: '一头牛加一头牛等于什么？', answer: '两头牛', options: ['犀牛', '牛牛', '两头牛', '双牛', '牛群', '奶牛'], explanation: '不要想复杂了，就是简单的加法！', difficulty: 'easy' },
  { id: 6, question: '什么门永远关不上？', answer: '球门', options: ['球门', '大门', '房门', '车门', '脑门', '嗓门'], explanation: '球门是敞开的，没有门板可关。', difficulty: 'easy' },
  { id: 7, question: '什么东西打碎了大家都叫好？', answer: '世界纪录', options: ['玻璃', '鸡蛋', '世界纪录', '碗', '花瓶', '杯子'], explanation: '打破世界纪录是一件好事。', difficulty: 'easy' },
  { id: 8, question: '什么车寸步难行？', answer: '风车', options: ['汽车', '风车', '自行车', '火车', '缆车', '雪车'], explanation: '风车是固定在地上的，不能移动。', difficulty: 'easy' },
  { id: 9, question: '什么东西始终不敢洗澡？', answer: '泥人', options: ['病人', '泥人', '懒人', '老人', '木头', '沙人'], explanation: '泥人洗澡会化掉。', difficulty: 'easy' },
  { id: 10, question: '什么东西能载百吨货却不能载一粒沙？', answer: '海水', options: ['大船', '火车', '飞机', '海水', '卡车', '气球'], explanation: '海水能承载大船百吨货，但一粒沙会被吞没消失。', difficulty: 'easy' },
  { id: 11, question: '什么海没有一滴水？', answer: '辞海', options: ['脑海', '死海', '辞海', '沙漠', '词海', '人海'], explanation: '《辞海》是一本词典，不是真正的海。', difficulty: 'easy' },
  { id: 12, question: '什么东西你天天在用却看不见？', answer: '空气', options: ['影子', '声音', '电', '空气', 'WiFi', '引力'], explanation: '空气每天都在呼吸使用，但肉眼看不见。', difficulty: 'easy' },
  { id: 13, question: '什么桥下没有水？', answer: '立交桥', options: ['彩虹', '天桥', '立交桥', '旱桥', '鹊桥', '心桥'], explanation: '立交桥在城市中，下面是道路不是水。', difficulty: 'easy' },
  { id: 14, question: '什么人一年只工作一天？', answer: '圣诞老人', options: ['圣诞老人', '教师', '生日主持人', '过年值班', '裁判', '考生'], explanation: '圣诞老人只在圣诞节送礼物。', difficulty: 'easy' },
  { id: 15, question: '什么东西有五个头但人不觉得它怪？', answer: '手', options: ['手', '星星', '五指山', '花', '蜈蚣', '海星'], explanation: '手有五个手指头（五个"头"），很正常。', difficulty: 'easy' },
  { id: 16, question: '什么东西能装下整个世界却只有巴掌大？', answer: '地图', options: ['地图', '镜子', '手机', '书本', '眼镜', '照片'], explanation: '地图能展示全世界，但只是一张纸。', difficulty: 'easy' },
  { id: 17, question: '什么东西外面绿里面红，外面怕水里面怕风？', answer: '西瓜', options: ['西瓜', '苹果', '辣椒', '番茄', '草莓', '樱桃'], explanation: '西瓜皮绿（怕水腐烂），瓤红（怕风吹干）。', difficulty: 'easy' },
  { id: 18, question: '什么东西你不打它它也不动你打了它它乱跳？', answer: '皮球', options: ['心脏', '闹钟', '皮球', '蚊子', '弹珠', '跳蚤'], explanation: '皮球不打不动，打了就会乱跳。', difficulty: 'easy' },
  { id: 19, question: '什么东西有嘴不说话有床不睡觉？', answer: '河', options: ['壶', '沙发', '枕头', '河', '碗', '锅'], explanation: '河有"河口"不说话，有"河床"不睡觉。', difficulty: 'easy' },
  { id: 20, question: '什么东西越旧越值钱？', answer: '古董', options: ['书', '古董', '衣服', '钱', '邮票', '酒'], explanation: '古董越老越珍贵。', difficulty: 'easy' },
  { id: 21, question: '什么笔不能写字？', answer: '电笔', options: ['电笔', '画笔', '毛笔', '铅笔', '眉笔', '录音笔'], explanation: '电笔是电工工具，用来测电不是写字。', difficulty: 'easy' },
  { id: 22, question: '什么书在书店买不到？', answer: '遗书', options: ['说明书', '教科书', '秘书', '遗书', '情书', '起诉书'], explanation: '遗书是个人遗言，书店不会卖。', difficulty: 'easy' },
  { id: 23, question: '什么水永远用不完？', answer: '口水', options: ['雨水', '泪水', '口水', '汗水', '墨水', '药水'], explanation: '口水是人体分泌的，理论上永远有。', difficulty: 'easy' },
  { id: 24, question: '什么东西越擦越小？', answer: '橡皮', options: ['毛巾', '橡皮', '抹布', '肥皂', '粉笔', '蜡烛'], explanation: '橡皮擦字会磨损变小。', difficulty: 'easy' },
  { id: 25, question: '什么东西比乌鸦更讨厌？', answer: '乌鸦嘴', options: ['苍蝇', '乌鸦嘴', '老鼠', '蚊子', '臭虫', '蟑螂'], explanation: '"乌鸦嘴"指说坏话的人，比乌鸦更招人烦。', difficulty: 'easy' },
  { id: 26, question: '什么人靠别人的脑袋生活？', answer: '理发师', options: ['理发师', '帽子商', '老师', '医生', '摄影师', '化妆师'], explanation: '理发师在别人的头（脑袋）上工作赚钱。', difficulty: 'easy' },
  { id: 27, question: '什么布剪不断？', answer: '瀑布', options: ['铁布', '棉布', '瀑布', '纱布', '抹布', '画布'], explanation: '瀑布是水流，剪刀剪不断水。', difficulty: 'easy' },
  { id: 28, question: '什么火看不见火焰？', answer: '怒火', options: ['磷火', '暗火', '怒火', '鬼火', '炉火', '心火'], explanation: '"怒火"是情绪，看不见真实火焰。', difficulty: 'easy' },
  { id: 29, question: '什么东西整天忙忙碌碌却什么也不做？', answer: '钟表', options: ['风扇', '陀螺', '钟表', '机器', '磨盘', '水车'], explanation: '钟表指针整天转动但不做任何实际事情。', difficulty: 'easy' },
  { id: 30, question: '什么东西没有脚却能走遍天下？', answer: '船', options: ['船', '钱', '信', '风', '鸟', '云'], explanation: '船没有脚但能在水上航行四方。', difficulty: 'easy' },

  // ===== Medium (31-65) =====
  { id: 31, question: '什么东西你站着它坐着你坐着它躺着？', answer: '脚印', options: ['脚印', '鞋', '椅子', '影子', '地毯', '垫子'], explanation: '站着时脚印在地上（坐着），坐着时脚印更平（躺着）。', difficulty: 'medium' },
  { id: 32, question: '什么东西你越生气它就越大？', answer: '脾气', options: ['气球', '火', '脾气', '声音', '拳头', '心跳'], explanation: '越生气脾气越大。', difficulty: 'medium' },
  { id: 33, question: '什么东西冬天最怕冷夏天最怕热？', answer: '雪人', options: ['病人', '胖子', '穷人', '雪人', '冰淇淋', '蜡像'], explanation: '雪人冬天怕再冷也化不了，夏天一热就融化。', difficulty: 'medium' },
  { id: 34, question: '什么东西最多却最不够用？', answer: '时间', options: ['钱', '粮食', '时间', '水', '空气', '爱'], explanation: '时间无处不在但总觉得不够。', difficulty: 'medium' },
  { id: 35, question: '什么花不能闻？', answer: '烟花', options: ['烟花', '棉花', '塑料花', '纸花', '浪花', '火花'], explanation: '烟花是火光不是真花，不能闻。', difficulty: 'medium' },
  { id: 36, question: '什么鱼不能吃？', answer: '木鱼', options: ['观赏鱼', '甲鱼', '鳄鱼', '木鱼', '鲸鱼', '章鱼'], explanation: '木鱼是寺庙敲击的法器，不是真鱼。', difficulty: 'medium' },
  { id: 37, question: '什么东西太阳晒不干风吹不走？', answer: '影子', options: ['石头', '影子', '房子', '沙子', '脚印', '回忆'], explanation: '影子跟着光线走，风吹不走，晒不干。', difficulty: 'medium' },
  { id: 38, question: '什么东西走路留下痕迹却看不到它本身？', answer: '脚印', options: ['脚印', '风', '雨', '车轮印', '影子', '气味'], explanation: '脚印能看到痕迹，但脚已经走了。', difficulty: 'medium' },
  { id: 39, question: '什么水要用力才能出来？', answer: '汗水', options: ['井水', '汗水', '泪水', '泉水', '奶水', '胶水'], explanation: '要用力运动才会出汗。', difficulty: 'medium' },
  { id: 40, question: '什么东西越热越爱出来？', answer: '汗', options: ['冰', '汗', '虫子', '蚊子', '蛇', '苍蝇'], explanation: '天气越热出汗越多。', difficulty: 'medium' },
  { id: 41, question: '什么人天天往医院跑却不是病人？', answer: '医生', options: ['医生', '护士', '保安', '院长', '快递员', '清洁工'], explanation: '医生每天在医院工作但不是病人。', difficulty: 'medium' },
  { id: 42, question: '什么东西能把昨天和明天连在一起？', answer: '今天', options: ['日历', '记忆', '今天', '钟表', '时间', '桥梁'], explanation: '今天连着昨天的结束和明天的开始。', difficulty: 'medium' },
  { id: 43, question: '什么最铁面无私？', answer: '秤', options: ['尺子', '法官', '秤', '镜子', '天平', '裁判'], explanation: '秤称东西不偏不倚，铁面无私。', difficulty: 'medium' },
  { id: 44, question: '什么洞最深？', answer: '黑洞', options: ['黑洞', '矿井', '井', '山洞', '陷阱', '迷宫'], explanation: '宇宙中的黑洞深不可测。', difficulty: 'medium' },
  { id: 45, question: '什么东西你拿着它它才能动你不拿它它就停？', answer: '扇子', options: ['钟表', '陀螺', '风筝', '扇子', '摇椅', '秋千'], explanation: '扇子要手摇才能动，放下就停。', difficulty: 'medium' },
  { id: 46, question: '什么东西不怕布只怕石头？', answer: '剪刀', options: ['锤子', '刀', '针', '剪刀', '锯子', '斧头'], explanation: '剪刀能剪布但剪不了石头。', difficulty: 'medium' },
  { id: 47, question: '什么人永远找不到工作？', answer: '死人', options: ['死人', '懒人', '犯人', '婴儿', '乞丐', '流浪汉'], explanation: '死人已经去世了，不可能找到工作。', difficulty: 'medium' },
  { id: 48, question: '什么东西你只能用左手拿右手拿不了？', answer: '右手', options: ['左耳', '右手', '心脏', '手表', '筷子', '左肩'], explanation: '你的右手不可能被右手自己拿住。', difficulty: 'medium' },
  { id: 49, question: '什么东西越冷越爱出来？', answer: '鼻涕', options: ['雪', '冰', '霜', '鼻涕', '冷气', '雾'], explanation: '天冷容易流鼻涕。', difficulty: 'medium' },
  { id: 50, question: '什么东西有牙齿不咬人？', answer: '梳子', options: ['拉链', '齿轮', '锯子', '梳子', '牙刷', '叉子'], explanation: '梳子有梳齿但不咬人。', difficulty: 'medium' },
  { id: 51, question: '什么房子不能住人？', answer: '蜂房', options: ['冰房', '蜂房', '帐篷', '纸房', '鸟巢', '狗窝'], explanation: '蜂房是蜜蜂住的，人不能住。', difficulty: 'medium' },
  { id: 52, question: '什么路最窄？', answer: '冤家路窄', options: ['冤家路窄', '山路', '钢丝', '小巷', '独木桥', '缝隙'], explanation: '"冤家路窄"是成语，形容路窄。', difficulty: 'medium' },
  { id: 53, question: '什么东西别人请你吃你却不吃？', answer: '亏', options: ['苦', '罚', '药', '亏', '醋', '苦头'], explanation: '"吃亏"别人请你但你不愿吃。', difficulty: 'medium' },
  { id: 54, question: '什么话全世界通用？', answer: '微笑', options: ['英语', '数学', '微笑', '音乐', '手势', '点头'], explanation: '微笑是全世界都能理解的语言。', difficulty: 'medium' },
  { id: 55, question: '什么东西你使劲也抓不住？', answer: '风', options: ['风', '沙', '烟', '水', '光', '雾'], explanation: '风看不见摸不着，使劲也抓不住。', difficulty: 'medium' },
  { id: 56, question: '什么东西越硬越容易碎？', answer: '玻璃', options: ['鸡蛋', '玻璃', '铁', '石头', '陶瓷', '冰'], explanation: '玻璃很硬但容易碎。', difficulty: 'medium' },
  { id: 57, question: '什么花最早开？', answer: '雪花', options: ['桃花', '雪花', '梅花', '迎春花', '菊花', '荷花'], explanation: '雪花在冬天就"开"了，比所有花都早。', difficulty: 'medium' },
  { id: 58, question: '什么东西最喜欢别人叫它滚？', answer: '车轮', options: ['演员', '圆柱', '球', '车轮', '滚筒', '磨盘'], explanation: '车轮就是要"滚"才能工作。', difficulty: 'medium' },
  { id: 59, question: '什么东西明明是圆的大家却说它是方的？', answer: '方向盘', options: ['方桌', '印章', '方向盘', '魔方', '车轮', '铜钱'], explanation: '方向盘是圆的但名字里有"方"。', difficulty: 'medium' },
  { id: 60, question: '什么数减1反倒变大？', answer: '分数', options: ['负数', '分数', '序数', '百分数', '倒数', '奇数'], explanation: '分数的分母减1，分数值反而变大。比如1/3比1/4大。', difficulty: 'medium' },
  { id: 61, question: '什么东西掉下来大家都很开心？', answer: '价格', options: ['礼物', '雨', '雪花', '价格', '红包', '落叶'], explanation: '价格掉下来（降价），大家开心。', difficulty: 'medium' },
  { id: 62, question: '什么东西人人都在用却叫不出名字？', answer: '空气', options: ['空气', '未来', '细菌', '银河', '思想', '运气'], explanation: '空气人人天天用但不说它名字。', difficulty: 'medium' },
  { id: 63, question: '什么东西一辈子都在挨打？', answer: '鼓', options: ['铁块', '乒乓球', '鼓', '锣', '钟', '砧板'], explanation: '鼓天天被人敲打（挨打）。', difficulty: 'medium' },
  { id: 64, question: '什么东西你打死它它流的是你的血？', answer: '蚊子', options: ['苍蝇', '蚊子', '跳蚤', '臭虫', '蜘蛛', '蚂蚁'], explanation: '打死蚊子，流出来的是你自己的血。', difficulty: 'medium' },
  { id: 65, question: '什么东西越黑越干净越白越脏？', answer: '黑板', options: ['黑板擦', '黑板', '煤炭', '墨水', '白纸', '白墙'], explanation: '黑板越黑说明没被粉笔弄脏（干净），越白说明粉笔痕迹多（脏）。', difficulty: 'medium' },

  // ===== Hard (66-100) =====
  { id: 66, question: '什么东西人人都有却都不愿意用？', answer: '遗嘱', options: ['钥匙', '遗嘱', '密码', '保险', '遗书', '存折'], explanation: '人人都会死有遗嘱，但都不愿用到（意味着死了）。', difficulty: 'hard' },
  { id: 67, question: '什么东西越没有越有人夸？', answer: '病', options: ['白发', '疤痕', '皱纹', '病', '缺点', '错误'], explanation: '没有病（健康）会被夸。', difficulty: 'hard' },
  { id: 68, question: '什么东西比大象还轻一粒沙却能挡住？', answer: '眼睛', options: ['鼻子', '耳朵', '嘴巴', '眼睛', '睫毛', '眼泪'], explanation: '眼睛很轻但一粒沙就睁不开。', difficulty: 'hard' },
  { id: 69, question: '什么东西走在路上总回头？', answer: '回头客', options: ['巡逻车', '模特', '侦探', '回头客', '出租车', '公交车'], explanation: '"回头客"名字就在回头。', difficulty: 'hard' },
  { id: 70, question: '什么东西最不怕冷最怕热？', answer: '雪人', options: ['雪人', '企鹅', '北极熊', '冰箱', '冰块', '冰棍'], explanation: '雪人不怕冷（本身就是雪），怕热融化。', difficulty: 'hard' },
  { id: 71, question: '什么东西明明是水却比冰还冷？', answer: '冰水', options: ['冷汗', '冰水', '干冰', '液氮', '霜', '寒泉'], explanation: '冰水混合物温度在零度以下。', difficulty: 'hard' },
  { id: 72, question: '什么东西你得把它弄坏才能用？', answer: '鸡蛋', options: ['信封', '锁', '鸡蛋', '包装', '胶囊', '坚果'], explanation: '鸡蛋壳弄破才能吃里面的。', difficulty: 'hard' },
  { id: 73, question: '什么东西大家都不想得到却经常得到？', answer: '感冒', options: ['烦恼', '批评', '罚款', '感冒', '受伤', '教训'], explanation: '没人想感冒但经常得感冒。', difficulty: 'hard' },
  { id: 74, question: '什么东西你早上看到晚上看不到？', answer: '阳光', options: ['阳光', '彩虹', '星星', '月亮', '朝霞', '露珠'], explanation: '早上有阳光，晚上没有。', difficulty: 'hard' },
  { id: 75, question: '什么东西明明是你的别人却用得比你还多？', answer: '名字', options: ['银行卡', '手机', '钥匙', '名字', '身份证', '照片'], explanation: '你的名字别人叫得多。', difficulty: 'hard' },
  { id: 76, question: '什么东西越多人踩越舒服？', answer: '路', options: ['沙发', '地毯', '路', '床', '草坪', '垫子'], explanation: '路被很多人踩，走起来反而更平坦舒服。', difficulty: 'hard' },
  { id: 77, question: '什么东西看起来像半个饼？', answer: '月亮', options: ['太阳', '半圆', '饼', '月亮', '彩虹', '拱门'], explanation: '半月像半个饼。', difficulty: 'hard' },
  { id: 78, question: '什么东西你自己看不到别人却能看到？', answer: '你的后脑勺', options: ['你的后脑勺', '影子', '脚印', '背', '你的后背', '你的耳朵'], explanation: '你自己看不到自己的后脑勺，别人能看到。', difficulty: 'hard' },
  { id: 79, question: '什么东西越想越想不起来？', answer: '梦', options: ['密码', '名字', '梦', '往事', '灵感', '遗忘'], explanation: '梦境越想回忆越模糊。', difficulty: 'hard' },
  { id: 80, question: '什么东西吃饭不用嘴？', answer: '蚕', options: ['蚕', '电脑', '婴儿', '机器人', '植物', '吸管'], explanation: '蚕吃桑叶不需要嘴（用颚啃食）。', difficulty: 'hard' },
  { id: 81, question: '什么东西四条腿早上出门两条腿中午回家三条腿晚上到？', answer: '人', options: ['椅子', '桌子', '人', '蜈蚣', '蜘蛛', '螃蟹'], explanation: '经典斯芬克斯之谜：婴儿爬行四腿，成人两腿，老人拄拐三腿。', difficulty: 'hard' },
  { id: 82, question: '什么东西一年只长一次？', answer: '年龄', options: ['年龄', '指甲', '树', '头发', '皱纹', '工资'], explanation: '年龄每年增长一次。', difficulty: 'hard' },
  { id: 83, question: '什么东西你丢掉它它还在你身边？', answer: '影子', options: ['气味', '记忆', '声音', '影子', '脚印', '习惯'], explanation: '丢不掉影子，它总在你旁边。', difficulty: 'hard' },
  { id: 84, question: '什么东西有头无脚能走千里？', answer: '火车', options: ['船', '火车', '信', '风', '火箭', '子弹'], explanation: '火车有车头无脚，能走千里。', difficulty: 'hard' },
  { id: 85, question: '什么东西你一生只有一次？', answer: '出生', options: ['出生', '死亡', '结婚', '毕业', '初恋', '高考'], explanation: '出生只有一次。', difficulty: 'hard' },
  { id: 86, question: '什么东西别人看不见你却天天看？', answer: '自己的脸', options: ['心跳', '梦', '自己的脸', '心思', '影子', '头发'], explanation: '你通过镜子看自己的脸，别人直接看。', difficulty: 'hard' },
  { id: 87, question: '什么东西只能往前走不能后退？', answer: '时间', options: ['年龄', '时间', '人生', '钟表', '光', '河流'], explanation: '时间永远向前流逝。', difficulty: 'hard' },
  { id: 88, question: '什么东西明明很小却装得下全世界？', answer: '眼睛', options: ['大脑', '心', '手机', '眼睛', '镜子', '地图'], explanation: '眼睛虽小但能看见全世界。', difficulty: 'hard' },
  { id: 89, question: '什么东西有翅膀却不会飞？', answer: '企鹅', options: ['鸵鸟', '企鹅', '飞机模型', '蝴蝶标本', '风筝', '天使像'], explanation: '企鹅有翅膀但不会飞。', difficulty: 'hard' },
  { id: 90, question: '什么东西最多人喜欢却最没人敢要？', answer: '免费', options: ['钱', '免费', '健康', '权力', '彩票', '红包'], explanation: '人人喜欢免费但没人敢要（怕陷阱）。', difficulty: 'hard' },
  { id: 91, question: '什么东西最硬又最软？', answer: '人心', options: ['人心', '钢铁', '棉花', '石头', '水', '空气'], explanation: '人心可以很硬（铁石心肠），也可以很软（心软）。', difficulty: 'hard' },
  { id: 92, question: '什么东西长了毛就表示成熟了？', answer: '玉米', options: ['猫', '桃子', '玉米', '人', '蒲公英', '棉花'], explanation: '玉米长出"玉米须"（毛）表示成熟了。', difficulty: 'hard' },
  { id: 93, question: '什么东西买了不用用了不买？', answer: '棺材', options: ['药', '锁', '保险', '棺材', '墓碑', '遗书'], explanation: '棺材买了不用（人还活着），用了不买（已死了）。', difficulty: 'hard' },
  { id: 94, question: '什么东西你只能看到一半？', answer: '月亮', options: ['地球', '球', '彩虹', '月亮', '半球', '半月饼'], explanation: '月亮永远只能看到一半（另一半在背面）。', difficulty: 'hard' },
  { id: 95, question: '什么人天天和老虎在一起却不怕老虎？', answer: '动物园饲养员', options: ['驯兽师', '猎人', '画家', '动物园饲养员', '兽医', '摄影师'], explanation: '饲养员天天喂老虎但了解它不怕。', difficulty: 'hard' },
  { id: 96, question: '什么东西吃了多反而少？', answer: '药', options: ['零食', '药', '饭', '水', '毒药', '酒'], explanation: '药吃多了反而命少了。', difficulty: 'hard' },
  { id: 97, question: '什么东西买的人知道卖的人也知道用的人不知道？', answer: '棺材', options: ['谜语', '保险', '遗书', '棺材', '礼物', '密码'], explanation: '买棺材的人（家属）知道，卖的人知道，用的人（死者）不知道。', difficulty: 'hard' },
  { id: 98, question: '什么东西你看不到摸不到却甩不掉？', answer: '影子', options: ['命运', '记忆', '烦恼', '影子', '风', '味道'], explanation: '影子看不到实体摸不到但甩不掉。', difficulty: 'hard' },
  { id: 99, question: '什么东西你越用越短别人越用越长？', answer: '铅笔', options: ['尺子', '铅笔', '绳子', '蜡烛', '香', '粉笔'], explanation: '铅笔自己用越短，别人用（你写字给别人看）越长。', difficulty: 'hard' },
  { id: 100, question: '什么东西今天做明天就不用做了？', answer: '作业', options: ['作业', '家务', '吃饭', '睡觉', '上班', '运动'], explanation: '今天的作业做了明天就不用再做同一份了。', difficulty: 'hard' },
]

export default RIDDLES