import type { Riddle } from '@wordcore/types'

const RIDDLES: Riddle[] = [
  // ===== Easy (1-30) =====
  { id: 1, hint: '千条线，万条线，掉到水里看不见', answer: '雨', options: ['雪', '雾', '雨', '冰'], explanation: '雨丝像千万条线，落入水中就看不见了。', category: 'nature', difficulty: 'easy' },
  { id: 2, hint: '有时落在山腰，有时挂在树梢，有时像面圆镜，有时像把镰刀', answer: '月亮', options: ['太阳', '月亮', '星星', '云彩'], explanation: '月亮的位置和形状会不断变化。', category: 'nature', difficulty: 'easy' },
  { id: 3, hint: '一个小姑娘，生在水中央，身穿粉红衫，坐在绿船上', answer: '荷花', options: ['荷花', '莲花', '水仙', '玫瑰'], explanation: '荷花从水中长出，粉色花瓣，绿色荷叶。', category: 'nature', difficulty: 'easy' },
  { id: 4, hint: '远看山有色，近听水无声，春去花还在，人来鸟不惊', answer: '画', options: ['画', '照片', '风景', '电视'], explanation: '画中的山水花鸟都是静止的。', category: 'object', difficulty: 'easy' },
  { id: 5, hint: '有面没有口，有脚没有手，虽有四条腿，自己不会走', answer: '桌子', options: ['桌子', '椅子', '床', '柜子'], explanation: '桌子有桌面（面）和四条桌腿（脚）。', category: 'object', difficulty: 'easy' },
  { id: 6, hint: '你哭他也哭，你笑他也笑，脸上脏不脏，看它就知道', answer: '镜子', options: ['镜子', '照片', '玻璃', '眼睛'], explanation: '镜子会忠实地反射你的表情。', category: 'object', difficulty: 'easy' },
  { id: 7, hint: '头戴红帽子，身穿白袍子，走路像公子，说话像猴子', answer: '鹅', options: ['鹅', '鸭子', '鸡', '天鹅'], explanation: '鹅头顶红色肉冠，全身白色羽毛，叫声响亮。', category: 'animal', difficulty: 'easy' },
  { id: 8, hint: '一个小小游泳家，说起话来呱呱呱，小时有尾没有脚，大了有脚没有尾', answer: '青蛙', options: ['青蛙', '蝌蚪', '鱼', '乌龟'], explanation: '青蛙小时候是蝌蚪，长大后尾巴消失长出四条腿。', category: 'animal', difficulty: 'easy' },
  { id: 9, hint: '年纪并不大，胡子一大把，不论遇见谁，总爱喊妈妈', answer: '羊', options: ['羊', '牛', '猫', '狗'], explanation: '羊的叫声"咩"听起来像叫"妈"。', category: 'animal', difficulty: 'easy' },
  { id: 10, hint: '嘴像小铲子，脚像小扇子，走路左右摆，水上划船子', answer: '鸭子', options: ['鸭子', '鹅', '鸡', '企鹅'], explanation: '鸭嘴扁宽，脚掌有蹼，走路摇摆，善游泳。', category: 'animal', difficulty: 'easy' },
  { id: 11, hint: '一个小姑娘，穿着黑衣裳，爱吃甜食不吃饭，整天忙碌采花忙', answer: '蜜蜂', options: ['蜜蜂', '蝴蝶', '苍蝇', '蜻蜓'], explanation: '蜜蜂采蜜忙碌不停。', category: 'animal', difficulty: 'easy' },
  { id: 12, hint: '一位好朋友，天天跟着走，你停他也停，你走他也走', answer: '影子', options: ['影子', '尾巴', '狗', '空气'], explanation: '影子随人移动，人停影停，人走影走。', category: 'other', difficulty: 'easy' },
  { id: 13, hint: '外面是绿的，里面是红的，吃的是甜的，吐出是黑的', answer: '西瓜', options: ['西瓜', '苹果', '番茄', '橙子'], explanation: '西瓜绿皮红瓤，黑籽吐出，甘甜多汁。', category: 'food', difficulty: 'easy' },
  { id: 14, hint: '麻屋子，红帐子，里面睡个白胖子', answer: '花生', options: ['花生', '瓜子', '核桃', '栗子'], explanation: '花生外壳像麻屋，红色内皮，白色花生仁。', category: 'food', difficulty: 'easy' },
  { id: 15, hint: '脱下红黄衣，七八个兄弟，紧紧抱一起', answer: '橘子', options: ['橘子', '橙子', '香蕉', '葡萄'], explanation: '橘子剥开外皮，里面一瓣一瓣紧抱在一起。', category: 'food', difficulty: 'easy' },
  { id: 16, hint: '上边毛，下边毛，中间一颗黑葡萄', answer: '眼睛', options: ['眼睛', '耳朵', '鼻子', '嘴巴'], explanation: '眼睛有上下睫毛，眼球像黑葡萄。', category: 'other', difficulty: 'easy' },
  { id: 17, hint: '左一片，右一片，隔座山头不见面', answer: '耳朵', options: ['耳朵', '眼睛', '眉毛', '肩膀'], explanation: '左右耳朵隔着脑袋互相看不见。', category: 'other', difficulty: 'easy' },
  { id: 18, hint: '十个兄弟一模样，五个短来五个长', answer: '手', options: ['手', '脚', '手指', '牙齿'], explanation: '两只手各有五根手指，长短不同。', category: 'other', difficulty: 'easy' },
  { id: 19, hint: '小时青，大时黄，结出棒子像拐杖', answer: '玉米', options: ['玉米', '高粱', '甘蔗', '竹子'], explanation: '玉米嫩时青绿，成熟后金黄。', category: 'food', difficulty: 'easy' },
  { id: 20, hint: '紫色树，开紫花，紫花谢了结紫瓜，紫瓜里面藏芝麻', answer: '茄子', options: ['茄子', '紫薯', '葡萄', '辣椒'], explanation: '茄子紫皮紫花，切开有许多小籽。', category: 'food', difficulty: 'easy' },
  { id: 21, hint: '弟兄七八个，围着柱子坐，只要一分开，衣服就撕破', answer: '蒜', options: ['蒜', '橘子', '花生', '豌豆'], explanation: '蒜瓣围在一起，掰开时外皮撕破。', category: 'food', difficulty: 'easy' },
  { id: 22, hint: '黄包袱，包黑豆，尝一口，甜水流', answer: '梨', options: ['梨', '苹果', '柿子', '橘子'], explanation: '黄梨皮像包袱，黑籽，咬一口甜水流出。', category: 'food', difficulty: 'easy' },
  { id: 23, hint: '说它是头牛，不会拉犁头，说它力气小，背着房子走', answer: '蜗牛', options: ['蜗牛', '乌龟', '牛', '田螺'], explanation: '蜗牛名中有牛但背壳走路很慢。', category: 'animal', difficulty: 'easy' },
  { id: 24, hint: '小小诸葛亮，独坐中军帐，摆下八卦阵，专捉飞来将', answer: '蜘蛛', options: ['蜘蛛', '蜜蜂', '蜻蜓', '蝴蝶'], explanation: '蜘蛛织网像八卦阵，等待飞虫自投罗网。', category: 'animal', difficulty: 'easy' },
  { id: 25, hint: '一条小虫，吃叶吐丝，结个白房，变成飞蛾', answer: '蚕', options: ['蚕', '蜜蜂', '毛毛虫', '蝴蝶'], explanation: '蚕吃桑叶吐丝结茧，破茧成蛾。', category: 'animal', difficulty: 'easy' },
  { id: 26, hint: '一种花儿真奇怪，冬天才开夏天败，无根无叶也无枝，漫天飞舞从天降', answer: '雪', options: ['雪', '霜', '花', '雨'], explanation: '雪花冬天飘落，没有根枝叶。', category: 'nature', difficulty: 'easy' },
  { id: 27, hint: '像棉不是棉，像烟不是烟，有时遮太阳，有时盖青山', answer: '云', options: ['云', '雾', '烟', '雪'], explanation: '云朵像棉絮烟雾，挡住太阳。', category: 'nature', difficulty: 'easy' },
  { id: 28, hint: '亮晶晶，硬邦邦，冬天水里生，太阳一晒就没影', answer: '冰', options: ['冰', '雪', '霜', '玻璃'], explanation: '冰是水在零度以下结成的固体。', category: 'nature', difficulty: 'easy' },
  { id: 29, hint: '青石板，板石青，青石板上钉银钉', answer: '星星', options: ['星星', '月亮', '灯', '萤火虫'], explanation: '夜空像青石板，星星像银钉。', category: 'nature', difficulty: 'easy' },
  { id: 30, hint: '身穿硬壳袍，缩头又缩脑，水里慢慢游，岸上慢慢走', answer: '乌龟', options: ['乌龟', '蜗牛', '螃蟹', '甲鱼'], explanation: '乌龟有硬壳，遇险缩头，动作缓慢。', category: 'animal', difficulty: 'easy' },

  // ===== Medium (31-65) =====
  { id: 31, hint: '有风不动无风动，不动无风动有风', answer: '扇子', options: ['扇子', '风筝', '风车', '旗子'], explanation: '天热无风时摇扇才有风，有风时反不用扇。', category: 'object', difficulty: 'medium' },
  { id: 32, hint: '一只蝴蝶轻轻飘，顺着风儿上九霄，可惜绳子拴住腰', answer: '风筝', options: ['风筝', '扇子', '蝴蝶', '飞机'], explanation: '风筝像蝴蝶飞上天，但被线拉住。', category: 'object', difficulty: 'medium' },
  { id: 33, hint: '小小一条龙，胡须硬如棕，生前没有血，死后满身红', answer: '虾', options: ['虾', '鱼', '蟹', '龙'], explanation: '虾须像棕丝，生时灰色，煮熟后变红。', category: 'animal', difficulty: 'medium' },
  { id: 34, hint: '像鱼不是鱼，长在大海里，头上有个喷水器', answer: '鲸鱼', options: ['鲸鱼', '鲨鱼', '海豚', '鱼'], explanation: '鲸鱼是哺乳动物，头顶有喷水孔换气。', category: 'animal', difficulty: 'medium' },
  { id: 35, hint: '头上两根毛，身穿花旗袍，成天不劳动，只知乐逍遥', answer: '蝴蝶', options: ['蝴蝶', '蜜蜂', '蜻蜓', '飞蛾'], explanation: '蝴蝶有两根触角，翅膀色彩艳丽。', category: 'animal', difficulty: 'medium' },
  { id: 36, hint: '不是糕点不是糖，洁白芬芳袋里装，不能吃来不能喝，每天你都要尝尝', answer: '牙膏', options: ['牙膏', '洗面奶', '洗衣粉', '牛奶'], explanation: '牙膏每天刷牙用，味道清新但不能吃。', category: 'object', difficulty: 'medium' },
  { id: 37, hint: '一间小房，没门没窗，敲开看看，黄白分明', answer: '鸡蛋', options: ['鸡蛋', '鸭蛋', '豆腐', '馒头'], explanation: '蛋壳像小房子，敲开蛋黄蛋白分明。', category: 'food', difficulty: 'medium' },
  { id: 38, hint: '一个老头，不跑不走，请他睡觉，他就摇头', answer: '不倒翁', options: ['不倒翁', '泥人', '娃娃', '石头'], explanation: '不倒翁推倒后会自己摇摆站起来。', category: 'object', difficulty: 'medium' },
  { id: 39, hint: '小小房子，窗子不大，里面有颗夜明珠，晚上照得亮堂堂', answer: '灯笼', options: ['灯笼', '电灯', '蜡烛', '手电筒'], explanation: '灯笼罩子像小房子，里面点灯照亮夜晚。', category: 'object', difficulty: 'medium' },
  { id: 40, hint: '一双玉燕靠地飞，早上出门晚上归', answer: '鞋子', options: ['鞋子', '袜子', '拖鞋', '车'], explanation: '鞋子像燕子贴地飞，早上穿晚上脱。', category: 'object', difficulty: 'medium' },
  { id: 41, hint: '嘴长腿短，专吃害虫，捉虫能手', answer: '啄木鸟', options: ['啄木鸟', '燕子', '麻雀', '公鸡'], explanation: '啄木鸟嘴巴尖长，啄开树皮捉害虫。', category: 'animal', difficulty: 'medium' },
  { id: 42, hint: '四季如春', answer: '长春', options: ['长春', '昆明', '贵阳', '永春'], explanation: '常年如春天——"长春"。', category: 'place', difficulty: 'medium' },
  { id: 43, hint: '两个胖子', answer: '合肥', options: ['合肥', '双鸭山', '胖城', '大连'], explanation: '两个胖子合在一起——"合"+"肥"。', category: 'place', difficulty: 'medium' },
  { id: 44, hint: '海上绿洲', answer: '青岛', options: ['青岛', '大连', '厦门', '珠海'], explanation: '海上的绿色岛屿——"青"+"岛"。', category: 'place', difficulty: 'medium' },
  { id: 45, hint: '久雨初晴', answer: '贵阳', options: ['贵阳', '晴隆', '日照', '昆明'], explanation: '久雨放晴——阳光很"贵"就是"贵阳"。', category: 'place', difficulty: 'medium' },
  { id: 46, hint: '一条彩带长又长，冬天围在脖子上', answer: '围巾', options: ['围巾', '领带', '围裙', '腰带'], explanation: '围巾像彩带，冬天保暖围在脖子上。', category: 'object', difficulty: 'medium' },
  { id: 47, hint: '十指分两边，从来不沾泥，冬天最受宠，夏天一边弃', answer: '手套', options: ['手套', '袜子', '围巾', '鞋垫'], explanation: '手套分五指，冬天保暖用。', category: 'object', difficulty: 'medium' },
  { id: 48, hint: '外面冷冰冰，里面热腾腾，倒出水来烫死人', answer: '暖水瓶', options: ['暖水瓶', '锅', '冰箱', '电饭煲'], explanation: '暖水瓶外壳不烫，内胆保温。', category: 'object', difficulty: 'medium' },
  { id: 49, hint: '小小木头，头戴红帽，擦一下，火就冒', answer: '火柴', options: ['火柴', '蜡烛', '打火机', '炭'], explanation: '火柴头含磷，摩擦生热点燃。', category: 'object', difficulty: 'medium' },
  { id: 50, hint: '细长身子，头上带线，流着眼泪，照亮夜晚', answer: '蜡烛', options: ['蜡烛', '火柴', '灯泡', '香'], explanation: '蜡烛点燃后熔化流下，照亮周围。', category: 'object', difficulty: 'medium' },
  { id: 51, hint: '小小骏马不会跑，日夜奔走不歇脚，提醒人们争分秒', answer: '时钟', options: ['时钟', '手表', '日历', '秒表'], explanation: '时钟指针日夜不停走动。', category: 'object', difficulty: 'medium' },
  { id: 52, hint: '小小细条，爱钻缝隙，身穿铁衣，头顶一线', answer: '针', options: ['针', '钉子', '铁丝', '牙签'], explanation: '针细长能钻过布料，针鼻穿线。', category: 'object', difficulty: 'medium' },
  { id: 53, hint: '一物生来怪，牙齿在嘴外，天天梳头用，从不上桌来', answer: '梳子', options: ['梳子', '刷子', '篦子', '叉子'], explanation: '梳子的齿在外部，用来梳头。', category: 'object', difficulty: 'medium' },
  { id: 54, hint: '兄弟两个一样长，一日三餐它们忙', answer: '筷子', options: ['筷子', '勺子', '叉子', '刀'], explanation: '两根筷子一样长，每日三餐用到。', category: 'object', difficulty: 'medium' },
  { id: 55, hint: '四四方方，有面有里，白天不用，晚上陪你', answer: '枕头', options: ['枕头', '被子', '床单', '沙发'], explanation: '枕头四方，睡觉用。', category: 'object', difficulty: 'medium' },
  { id: 56, hint: '铜头铁臂小将军，把守大门不离分', answer: '锁', options: ['锁', '门', '钥匙', '插销'], explanation: '锁像将军看门，没有钥匙打不开。', category: 'object', difficulty: 'medium' },
  { id: 57, hint: '小铁片，不长眼，插进门里转一转，门就开了', answer: '钥匙', options: ['钥匙', '锁', '把手', '插销'], explanation: '钥匙插进锁孔转动开锁。', category: 'object', difficulty: 'medium' },
  { id: 58, hint: '白肚皮，黑外衣，住在南极不会飞，走起路来摇又摆', answer: '企鹅', options: ['企鹅', '熊猫', '海豹', '鸭子'], explanation: '企鹅白腹黑背，南极特有，不会飞。', category: 'animal', difficulty: 'medium' },
  { id: 59, hint: '背上两座山，沙漠里面行，不怕渴和饿', answer: '骆驼', options: ['骆驼', '马', '牛', '大象'], explanation: '骆驼驼峰像两座山，耐渴耐饿。', category: 'animal', difficulty: 'medium' },
  { id: 60, hint: '像马不是马，海里来安家，卷起长尾巴，直立水中游', answer: '海马', options: ['海马', '海豚', '海豹', '鲨鱼'], explanation: '海马头似马，有卷尾，水中直立。', category: 'animal', difficulty: 'medium' },
  { id: 61, hint: '一碗水，半碗泥，从古到今流万里', answer: '黄河', options: ['黄河', '长江', '淮河', '珠江'], explanation: '黄河含沙量大，水色黄浊。', category: 'place', difficulty: 'medium' },
  { id: 62, hint: '一条巨龙，横跨山河，不到此处，不算好汉', answer: '长城', options: ['长城', '长江', '黄河', '故宫'], explanation: '长城像巨龙蜿蜒山间。', category: 'place', difficulty: 'medium' },
  { id: 63, hint: '天府之地，熊猫故乡，美食之都', answer: '成都', options: ['成都', '重庆', '西安', '昆明'], explanation: '成都是天府之国，大熊猫故乡。', category: 'place', difficulty: 'medium' },
  { id: 64, hint: '山中有城，城中有山，火锅飘香', answer: '重庆', options: ['重庆', '成都', '贵阳', '昆明'], explanation: '重庆是山城，以火锅闻名。', category: 'place', difficulty: 'medium' },
  { id: 65, hint: '上有天堂，下有苏杭', answer: '苏州', options: ['苏州', '杭州', '扬州', '南京'], explanation: '苏杭指苏州和杭州，园林之城。', category: 'place', difficulty: 'medium' },

  // ===== Hard (66-100) =====
  { id: 66, hint: '红口袋，绿口袋，有人怕，有人爱，爱它是美味，怕它辣眼泪', answer: '辣椒', options: ['辣椒', '番茄', '柿子', '草莓'], explanation: '辣椒爱吃的人觉得香，怕吃的人辣得流泪。', category: 'food', difficulty: 'hard' },
  { id: 67, hint: '石匠不识字，却爱认字多，认来又认去，就是认不着', answer: '石碑', options: ['石碑', '石匠', '课本', '招牌'], explanation: '石碑上刻满字，但石头不识字。', category: 'object', difficulty: 'hard' },
  { id: 68, hint: '一只小虫，尾巴发光，飞来飞去，像颗星星', answer: '萤火虫', options: ['萤火虫', '蜻蜓', '蜜蜂', '星星'], explanation: '萤火虫尾部发光，夏夜飞行像星星。', category: 'animal', difficulty: 'hard' },
  { id: 69, hint: '肚子里空空，节日就发红，高高挂门前，照得乐融融', answer: '灯笼', options: ['灯笼', '对联', '鞭炮', '红旗'], explanation: '灯笼中空，节日挂在大门前。', category: 'object', difficulty: 'hard' },
  { id: 70, hint: '有它不在白天，无它不在夜晚，说它从未露面，其实就在眼前', answer: '黑暗', options: ['黑暗', '影子', '梦', '空气'], explanation: '黑暗白天没有，夜晚无处不在。', category: 'nature', difficulty: 'hard' },
  { id: 71, hint: '天上飞，不是鸟，前头翅膀大，后头翅膀小', answer: '飞机', options: ['飞机', '鸟', '风筝', '蝴蝶'], explanation: '飞机前翼大后翼小，在天上飞。', category: 'object', difficulty: 'hard' },
  { id: 72, hint: '没到手也想它，到手了也摸它，偏偏不在手里，却叫你说出它', answer: '谜语', options: ['谜语', '梦', '风', '声音'], explanation: '谜语本身——猜到答案前在想它，说出来却不在手里。', category: 'other', difficulty: 'hard' },
  { id: 73, hint: '银河渡口', answer: '天津', options: ['天津', '汉口', '海口', '江门'], explanation: '银河（天）上的渡口（津）——"天津"。', category: 'place', difficulty: 'hard' },
  { id: 74, hint: '大家都笑你', answer: '齐齐哈尔', options: ['齐齐哈尔', '哈尔滨', '西安', '大连'], explanation: '大家（齐齐）笑（哈）你（尔）——齐齐哈尔。', category: 'place', difficulty: 'hard' },
  { id: 75, hint: '没有夏天', answer: '宁夏', options: ['宁夏', '长春', '贵阳', '西安'], explanation: '"宁"可没有"夏"——"宁夏"。', category: 'place', difficulty: 'hard' },
  { id: 76, hint: '一物生来真奇怪，身穿三百多件衣，每天给它脱一件，脱到年底剩张皮', answer: '日历', options: ['日历', '书', '衣服', '洋葱'], explanation: '日历每天撕一页，一年撕完剩封皮。', category: 'object', difficulty: 'hard' },
  { id: 77, hint: '乍看白茫茫，细看一条江，没有鱼和虾，只有船来往', answer: '马路', options: ['马路', '江河', '雪地', '银河'], explanation: '路面像江，车像船来往。', category: 'object', difficulty: 'hard' },
  { id: 78, hint: '一物生来真奇怪，腰里长个袋，袋里长个碗，碗里长个筷', answer: '枣', options: ['枣', '花生', '核桃', '栗子'], explanation: '枣身像袋子，里面有核。', category: 'food', difficulty: 'hard' },
  { id: 79, hint: '有风吹不动，没风自己摇。天热离不了，天冷一边抛', answer: '扇子', options: ['扇子', '树', '旗子', '风筝'], explanation: '扇子没风时摇动生风。', category: 'object', difficulty: 'hard' },
  { id: 80, hint: '生在水中，就怕水冲，一到水里，无影无踪', answer: '盐', options: ['盐', '糖', '冰', '沙'], explanation: '盐遇水溶解消失。', category: 'food', difficulty: 'hard' },
  { id: 81, hint: '夜里做，白日忘，闭上眼就来，睁开眼就跑', answer: '梦', options: ['梦', '影子', '回忆', '想象'], explanation: '梦在睡眠中出现，醒来忘记。', category: 'other', difficulty: 'hard' },
  { id: 82, hint: '看不见，摸不着，没有它，活不了', answer: '空气', options: ['空气', '水', '阳光', '食物'], explanation: '空气看不见摸不着，但人离不开它。', category: 'nature', difficulty: 'hard' },
  { id: 83, hint: '一座七彩桥，雨后天上挂，人人说好看，就是走不上', answer: '彩虹', options: ['彩虹', '桥', '晚霞', '银河'], explanation: '彩虹是雨后光学现象。', category: 'nature', difficulty: 'hard' },
  { id: 84, hint: '一头牛，两个头，这头喝水那头流', answer: '水管', options: ['水管', '井', '水龙头', '河'], explanation: '水管一头进水另一头出水。', category: 'object', difficulty: 'hard' },
  { id: 85, hint: '不是路，不是房，架在河上连两方', answer: '桥', options: ['桥', '船', '路', '坝'], explanation: '桥架在河上连接两岸。', category: 'object', difficulty: 'hard' },
  { id: 86, hint: '一条带子长又长，四通八达通四方', answer: '路', options: ['路', '河', '桥', '绳'], explanation: '路像长带子通向四面八方。', category: 'other', difficulty: 'hard' },
  { id: 87, hint: '看不见，摸不着，一按开关就来了', answer: '电', options: ['电', '风', '声音', '光'], explanation: '电看不见摸不着，开关一按就来。', category: 'other', difficulty: 'hard' },
  { id: 88, hint: '不是金，不是银，铁见它就往上贴', answer: '磁铁', options: ['磁铁', '石头', '铁', '胶水'], explanation: '磁铁能吸引铁质物品。', category: 'object', difficulty: 'hard' },
  { id: 89, hint: '一口大碗没有底，千桶万桶装不满', answer: '井', options: ['井', '缸', '湖', '碗'], explanation: '井很深，打多少水也装不满。', category: 'object', difficulty: 'hard' },
  { id: 90, hint: '看着小小不起眼，千斤万两它能掂', answer: '秤', options: ['秤', '尺子', '钟表', '算盘'], explanation: '秤虽小能称重物。', category: 'object', difficulty: 'hard' },
  { id: 91, hint: '一只眼睛长又长，远处东西看得清', answer: '望远镜', options: ['望远镜', '显微镜', '眼镜', '放大镜'], explanation: '望远镜像长眼睛，看清远处。', category: 'object', difficulty: 'hard' },
  { id: 92, hint: '一张皮，两面蒙，敲敲打打响咚咚', answer: '鼓', options: ['鼓', '锣', '钟', '铃'], explanation: '鼓两面蒙皮，敲击发声。', category: 'object', difficulty: 'hard' },
  { id: 93, hint: '一条白带挂山前，飞流直下三千尺', answer: '瀑布', options: ['瀑布', '河流', '雪崩', '白云'], explanation: '瀑布从山顶倾泻而下。', category: 'nature', difficulty: 'hard' },
  { id: 94, hint: '一个金球圆又圆，早晨出山晚上落', answer: '太阳', options: ['太阳', '月亮', '星星', '灯笼'], explanation: '太阳像金球东升西落。', category: 'nature', difficulty: 'hard' },
  { id: 95, hint: '看不见来摸不着，树摇水动就知道', answer: '风', options: ['风', '电', '声音', '空气'], explanation: '风无形无色，树摇水动可知。', category: 'nature', difficulty: 'hard' },
  { id: 96, hint: '像云不是云，像烟不是烟，山间常出现，十步不见人', answer: '雾', options: ['雾', '云', '烟', '霜'], explanation: '雾是近地面的云，能见度低。', category: 'nature', difficulty: 'hard' },
  { id: 97, hint: '冬天早上白花花，太阳一出就化啦', answer: '霜', options: ['霜', '雪', '雾', '冰'], explanation: '霜是低温时凝结的白色晶体。', category: 'nature', difficulty: 'hard' },
  { id: 98, hint: '夜里结成，早上出现，太阳一照，眨眼不见', answer: '露珠', options: ['露珠', '霜', '雾', '雨'], explanation: '露珠是夜间水汽凝结的水滴。', category: 'nature', difficulty: 'hard' },
  { id: 99, hint: '一个圆家伙，抽它它就转，不抽它就站', answer: '陀螺', options: ['陀螺', '球', '轮子', '硬币'], explanation: '陀螺抽打才转，不抽就停。', category: 'object', difficulty: 'hard' },
  { id: 100, hint: '头戴尖尖帽，身穿节节衣，春天钻出土，雨后长得高', answer: '竹笋', options: ['竹笋', '竹子', '玉米', '甘蔗'], explanation: '竹笋尖尖的，有节，春天雨后快速生长。', category: 'nature', difficulty: 'hard' },
]

export default RIDDLES
