import type { FillEntry } from './types'

const ENTRIES: FillEntry[] = [
  // ===== Easy (1-30) =====
  { id: 1, line: '床前明___光', blank: '___', answer: '月', options: ['星', '风', '月', '雪'], title: '静夜思', author: '李白', dynasty: '唐', difficulty: 'easy' },
  { id: 2, line: '春眠不觉___', blank: '___', answer: '晓', options: ['晨', '晓', '寒', '夜'], title: '春晓', author: '孟浩然', dynasty: '唐', difficulty: 'easy' },
  { id: 3, line: '处处闻___鸟', blank: '___', answer: '啼', options: ['鸣', '啼', '归', '飞'], title: '春晓', author: '孟浩然', dynasty: '唐', difficulty: 'easy' },
  { id: 4, line: '白日依___尽', blank: '___', answer: '山', options: ['云', '河', '天', '山'], title: '登鹳雀楼', author: '王之涣', dynasty: '唐', difficulty: 'easy' },
  { id: 5, line: '黄河入___流', blank: '___', answer: '海', options: ['湖', '海', '川', '江'], title: '登鹳雀楼', author: '王之涣', dynasty: '唐', difficulty: 'easy' },
  { id: 6, line: '锄___日当午', blank: '___', answer: '禾', options: ['禾', '草', '麦', '田'], title: '悯农', author: '李绅', dynasty: '唐', difficulty: 'easy' },
  { id: 7, line: '汗滴___下土', blank: '___', answer: '禾', options: ['麦', '田', '地', '禾'], title: '悯农', author: '李绅', dynasty: '唐', difficulty: 'easy' },
  { id: 8, line: '离离原上___', blank: '___', answer: '草', options: ['叶', '花', '草', '树'], title: '赋得古原草送别', author: '白居易', dynasty: '唐', difficulty: 'easy' },
  { id: 9, line: '一___一枯荣', blank: '___', answer: '岁', options: ['秋', '岁', '春', '年'], title: '赋得古原草送别', author: '白居易', dynasty: '唐', difficulty: 'easy' },
  { id: 10, line: '野火烧不___', blank: '___', answer: '尽', options: ['断', '灭', '绝', '尽'], title: '赋得古原草送别', author: '白居易', dynasty: '唐', difficulty: 'easy' },
  { id: 11, line: '___风吹又生', blank: '___', answer: '春', options: ['春', '秋', '寒', '暖'], title: '赋得古原草送别', author: '白居易', dynasty: '唐', difficulty: 'easy' },
  { id: 12, line: '千___鸟飞绝', blank: '___', answer: '山', options: ['林', '山', '江', '水'], title: '江雪', author: '柳宗元', dynasty: '唐', difficulty: 'easy' },
  { id: 13, line: '万径人___灭', blank: '___', answer: '踪', options: ['影', '迹', '踪', '声'], title: '江雪', author: '柳宗元', dynasty: '唐', difficulty: 'easy' },
  { id: 14, line: '两个___鹂鸣翠柳', blank: '___', answer: '黄', options: ['黄', '白', '青', '红'], title: '绝句', author: '杜甫', dynasty: '唐', difficulty: 'easy' },
  { id: 15, line: '一行___鹭上青天', blank: '___', answer: '白', options: ['青', '黄', '黑', '白'], title: '绝句', author: '杜甫', dynasty: '唐', difficulty: 'easy' },
  { id: 16, line: '___在异乡为异客', blank: '___', answer: '独', options: ['孤', '独', '人', '客'], title: '九月九日忆山东兄弟', author: '王维', dynasty: '唐', difficulty: 'easy' },
  { id: 17, line: '每逢___节倍思亲', blank: '___', answer: '佳', options: ['节', '春', '佳', '秋'], title: '九月九日忆山东兄弟', author: '王维', dynasty: '唐', difficulty: 'easy' },
  { id: 18, line: '好___知时节', blank: '___', answer: '雨', options: ['霜', '雨', '风', '雪'], title: '春夜喜雨', author: '杜甫', dynasty: '唐', difficulty: 'easy' },
  { id: 19, line: '当___乃发生', blank: '___', answer: '春', options: ['冬', '夏', '秋', '春'], title: '春夜喜雨', author: '杜甫', dynasty: '唐', difficulty: 'easy' },
  { id: 20, line: '月落___啼霜满天', blank: '___', answer: '乌', options: ['鸦', '乌', '鸟', '雁'], title: '枫桥夜泊', author: '张继', dynasty: '唐', difficulty: 'easy' },
  { id: 21, line: '___母手中线', blank: '___', answer: '慈', options: ['慈', '母', '善', '贤'], title: '游子吟', author: '孟郊', dynasty: '唐', difficulty: 'easy' },
  { id: 22, line: '游___身上衣', blank: '___', answer: '子', options: ['人', '子', '客', '儿'], title: '游子吟', author: '孟郊', dynasty: '唐', difficulty: 'easy' },
  { id: 23, line: '朝辞白帝___云间', blank: '___', answer: '彩', options: ['彩', '乌', '白', '烟'], title: '早发白帝城', author: '李白', dynasty: '唐', difficulty: 'easy' },
  { id: 24, line: '千___江陵一日还', blank: '___', answer: '里', options: ['步', '里', '丈', '尺'], title: '早发白帝城', author: '李白', dynasty: '唐', difficulty: 'easy' },
  { id: 25, line: '大___孤烟直', blank: '___', answer: '漠', options: ['野', '河', '漠', '山'], title: '使至塞上', author: '王维', dynasty: '唐', difficulty: 'easy' },
  { id: 26, line: '清明时节雨___', blank: '___', answer: '纷', options: ['洒', '飘', '落', '纷'], title: '清明', author: '杜牧', dynasty: '唐', difficulty: 'easy' },
  { id: 27, line: '___豆生南国', blank: '___', answer: '红', options: ['白', '绿', '红', '黄'], title: '相思', author: '王维', dynasty: '唐', difficulty: 'easy' },
  { id: 28, line: '___看成岭侧成峰', blank: '___', answer: '横', options: ['横', '纵', '侧', '正'], title: '题西林壁', author: '苏轼', dynasty: '宋', difficulty: 'easy' },
  { id: 29, line: '不识庐___真面目', blank: '___', answer: '山', options: ['山', '峰', '水', '云'], title: '题西林壁', author: '苏轼', dynasty: '宋', difficulty: 'easy' },
  { id: 30, line: '但___人长久', blank: '___', answer: '愿', options: ['愿', '盼', '求', '望'], title: '水调歌头', author: '苏轼', dynasty: '宋', difficulty: 'easy' },

  // ===== Medium (31-65) =====
  { id: 31, line: '海内___知己', blank: '___', answer: '存', options: ['无', '求', '有', '存'], title: '送杜少府之任蜀州', author: '王勃', dynasty: '唐', difficulty: 'medium' },
  { id: 32, line: '___涯若比邻', blank: '___', answer: '天', options: ['地', '山', '天', '海'], title: '送杜少府之任蜀州', author: '王勃', dynasty: '唐', difficulty: 'medium' },
  { id: 33, line: '随风___入夜', blank: '___', answer: '潜', options: ['潜', '入', '飘', '落'], title: '春夜喜雨', author: '杜甫', dynasty: '唐', difficulty: 'medium' },
  { id: 34, line: '润___细无声', blank: '___', answer: '物', options: ['花', '土', '物', '草'], title: '春夜喜雨', author: '杜甫', dynasty: '唐', difficulty: 'medium' },
  { id: 35, line: '春蚕到___丝方尽', blank: '___', answer: '死', options: ['终', '死', '老', '枯'], title: '无题', author: '李商隐', dynasty: '唐', difficulty: 'medium' },
  { id: 36, line: '蜡炬成___泪始干', blank: '___', answer: '灰', options: ['灰', '炭', '烟', '烬'], title: '无题', author: '李商隐', dynasty: '唐', difficulty: 'medium' },
  { id: 37, line: '___君更尽一杯酒', blank: '___', answer: '劝', options: ['劝', '留', '请', '邀'], title: '送元二使安西', author: '王维', dynasty: '唐', difficulty: 'medium' },
  { id: 38, line: '西出阳___无故人', blank: '___', answer: '关', options: ['道', '门', '路', '关'], title: '送元二使安西', author: '王维', dynasty: '唐', difficulty: 'medium' },
  { id: 39, line: '停车___爱枫林晚', blank: '___', answer: '坐', options: ['立', '行', '坐', '驻'], title: '山行', author: '杜牧', dynasty: '唐', difficulty: 'medium' },
  { id: 40, line: '霜叶___于二月花', blank: '___', answer: '红', options: ['白', '绿', '红', '黄'], title: '山行', author: '杜牧', dynasty: '唐', difficulty: 'medium' },
  { id: 41, line: '谁___寸草心', blank: '___', answer: '言', options: ['言', '道', '知', '说'], title: '游子吟', author: '孟郊', dynasty: '唐', difficulty: 'medium' },
  { id: 42, line: '报得三___晖', blank: '___', answer: '春', options: ['秋', '阳', '晨', '春'], title: '游子吟', author: '孟郊', dynasty: '唐', difficulty: 'medium' },
  { id: 43, line: '飞流___下三千尺', blank: '___', answer: '直', options: ['落', '坠', '直', '倾'], title: '望庐山瀑布', author: '李白', dynasty: '唐', difficulty: 'medium' },
  { id: 44, line: '疑是银___落九天', blank: '___', answer: '河', options: ['汉', '川', '星', '河'], title: '望庐山瀑布', author: '李白', dynasty: '唐', difficulty: 'medium' },
  { id: 45, line: '___卧沙场君莫笑', blank: '___', answer: '醉', options: ['醉', '死', '卧', '战'], title: '凉州词', author: '王翰', dynasty: '唐', difficulty: 'medium' },
  { id: 46, line: '古来___战几人回', blank: '___', answer: '征', options: ['战', '征', '杀', '斗'], title: '凉州词', author: '王翰', dynasty: '唐', difficulty: 'medium' },
  { id: 47, line: '借问___家何处有', blank: '___', answer: '酒', options: ['茶', '酒', '客', '花'], title: '清明', author: '杜牧', dynasty: '唐', difficulty: 'medium' },
  { id: 48, line: '牧童遥___杏花村', blank: '___', answer: '指', options: ['引', '指', '说', '望'], title: '清明', author: '杜牧', dynasty: '唐', difficulty: 'medium' },
  { id: 49, line: '莫愁前___无知己', blank: '___', answer: '路', options: ['程', '途', '道', '路'], title: '别董大', author: '高适', dynasty: '唐', difficulty: 'medium' },
  { id: 50, line: '___下问童子', blank: '___', answer: '松', options: ['梅', '松', '竹', '柳'], title: '寻隐者不遇', author: '贾岛', dynasty: '唐', difficulty: 'medium' },
  { id: 51, line: '只在此___中', blank: '___', answer: '山', options: ['山', '谷', '林', '洞'], title: '寻隐者不遇', author: '贾岛', dynasty: '唐', difficulty: 'medium' },
  { id: 52, line: '___深不知处', blank: '___', answer: '云', options: ['林', '雾', '云', '烟'], title: '寻隐者不遇', author: '贾岛', dynasty: '唐', difficulty: 'medium' },
  { id: 53, line: '忽如一夜___风来', blank: '___', answer: '春', options: ['春', '暖', '秋', '寒'], title: '白雪歌送武判官归京', author: '岑参', dynasty: '唐', difficulty: 'medium' },
  { id: 54, line: '千___万树梨花开', blank: '___', answer: '树', options: ['山', '花', '枝', '树'], title: '白雪歌送武判官归京', author: '岑参', dynasty: '唐', difficulty: 'medium' },
  { id: 55, line: '___当作人杰', blank: '___', answer: '生', options: ['死', '命', '天', '生'], title: '夏日绝句', author: '李清照', dynasty: '宋', difficulty: 'medium' },
  { id: 56, line: '死亦为___雄', blank: '___', answer: '鬼', options: ['鬼', '豪', '英', '将'], title: '夏日绝句', author: '李清照', dynasty: '宋', difficulty: 'medium' },
  { id: 57, line: '采___东篱下', blank: '___', answer: '菊', options: ['菊', '梅', '花', '茶'], title: '饮酒', author: '陶渊明', dynasty: '东晋', difficulty: 'medium' },
  { id: 58, line: '悠___见南山', blank: '___', answer: '然', options: ['尔', '哉', '乎', '然'], title: '饮酒', author: '陶渊明', dynasty: '东晋', difficulty: 'medium' },
  { id: 59, line: '问渠那得___如许', blank: '___', answer: '清', options: ['净', '清', '深', '明'], title: '观书有感', author: '朱熹', dynasty: '宋', difficulty: 'medium' },
  { id: 60, line: '为有___头活水来', blank: '___', answer: '源', options: ['始', '头', '泉', '源'], title: '观书有感', author: '朱熹', dynasty: '宋', difficulty: 'medium' },
  { id: 61, line: '竹外___花三两枝', blank: '___', answer: '桃', options: ['梨', '梅', '桃', '杏'], title: '惠崇春江晚景', author: '苏轼', dynasty: '宋', difficulty: 'medium' },
  { id: 62, line: '春___水暖鸭先知', blank: '___', answer: '江', options: ['河', '江', '湖', '溪'], title: '惠崇春江晚景', author: '苏轼', dynasty: '宋', difficulty: 'medium' },
  { id: 63, line: '等___识得东风面', blank: '___', answer: '闲', options: ['闲', '要', '忙', '须'], title: '春日', author: '朱熹', dynasty: '宋', difficulty: 'medium' },
  { id: 64, line: '万___千红总是春', blank: '___', answer: '紫', options: ['紫', '青', '黄', '白'], title: '春日', author: '朱熹', dynasty: '宋', difficulty: 'medium' },
  { id: 65, line: '粉身碎___浑不怕', blank: '___', answer: '骨', options: ['身', '肉', '血', '骨'], title: '石灰吟', author: '于谦', dynasty: '明', difficulty: 'medium' },

  // ===== Hard (66-100) =====
  { id: 66, line: '落___与孤鹜齐飞', blank: '___', answer: '霞', options: ['日', '雨', '花', '霞'], title: '滕王阁序', author: '王勃', dynasty: '唐', difficulty: 'hard' },
  { id: 67, line: '秋___共长天一色', blank: '___', answer: '水', options: ['月', '水', '云', '风'], title: '滕王阁序', author: '王勃', dynasty: '唐', difficulty: 'hard' },
  { id: 68, line: '会挽___弓如满月', blank: '___', answer: '雕', options: ['长', '硬', '雕', '铁'], title: '江城子·密州出猎', author: '苏轼', dynasty: '宋', difficulty: 'hard' },
  { id: 69, line: '安能___眉折腰事权贵', blank: '___', answer: '摧', options: ['俯', '摧', '低', '弯'], title: '梦游天姥吟留别', author: '李白', dynasty: '唐', difficulty: 'hard' },
  { id: 70, line: '出师未___身先死', blank: '___', answer: '捷', options: ['功', '战', '胜', '捷'], title: '蜀相', author: '杜甫', dynasty: '唐', difficulty: 'hard' },
  { id: 71, line: '长使英雄___满襟', blank: '___', answer: '泪', options: ['悲', '汗', '泪', '血'], title: '蜀相', author: '杜甫', dynasty: '唐', difficulty: 'hard' },
  { id: 72, line: '曾经___海难为水', blank: '___', answer: '沧', options: ['大', '沧', '深', '碧'], title: '离思', author: '元稹', dynasty: '唐', difficulty: 'hard' },
  { id: 73, line: '除却___山不是云', blank: '___', answer: '巫', options: ['仙', '巫', '神', '灵'], title: '离思', author: '元稹', dynasty: '唐', difficulty: 'hard' },
  { id: 74, line: '风萧___兮易水寒', blank: '___', answer: '萧', options: ['凄', '瑟', '冷', '萧'], title: '易水歌', author: '荆轲', dynasty: '先秦', difficulty: 'hard' },
  { id: 75, line: '大___东去浪淘尽', blank: '___', answer: '江', options: ['海', '河', '江', '水'], title: '念奴娇·赤壁怀古', author: '苏轼', dynasty: '宋', difficulty: 'hard' },
  { id: 76, line: '身无彩___双飞翼', blank: '___', answer: '凤', options: ['凤', '龙', '鸟', '蝶'], title: '无题', author: '李商隐', dynasty: '唐', difficulty: 'hard' },
  { id: 77, line: '心有___犀一点通', blank: '___', answer: '灵', options: ['聪', '神', '明', '灵'], title: '无题', author: '李商隐', dynasty: '唐', difficulty: 'hard' },
  { id: 78, line: '同是天___沦落人', blank: '___', answer: '涯', options: ['下', '地', '边', '涯'], title: '琵琶行', author: '白居易', dynasty: '唐', difficulty: 'hard' },
  { id: 79, line: '相逢何必曾相___', blank: '___', answer: '识', options: ['遇', '见', '知', '识'], title: '琵琶行', author: '白居易', dynasty: '唐', difficulty: 'hard' },
  { id: 80, line: '黑___压城城欲摧', blank: '___', answer: '云', options: ['云', '烟', '雾', '风'], title: '雁门太守行', author: '李贺', dynasty: '唐', difficulty: 'hard' },
  { id: 81, line: '___光向日金鳞开', blank: '___', answer: '甲', options: ['枪', '甲', '刀', '剑'], title: '雁门太守行', author: '李贺', dynasty: '唐', difficulty: 'hard' },
  { id: 82, line: '年年___岁花相似', blank: '___', answer: '岁', options: ['春', '日', '月', '岁'], title: '代悲白头翁', author: '刘希夷', dynasty: '唐', difficulty: 'hard' },
  { id: 83, line: '___岁年年人不同', blank: '___', answer: '岁', options: ['岁', '朝', '年', '日'], title: '代悲白头翁', author: '刘希夷', dynasty: '唐', difficulty: 'hard' },
  { id: 84, line: '枝上柳___吹又少', blank: '___', answer: '绵', options: ['叶', '绵', '花', '絮'], title: '蝶恋花', author: '苏轼', dynasty: '宋', difficulty: 'hard' },
  { id: 85, line: '人___自古谁无死', blank: '___', answer: '生', options: ['世', '生', '间', '命'], title: '过零丁洋', author: '文天祥', dynasty: '宋', difficulty: 'hard' },
  { id: 86, line: '留取丹心照___青', blank: '___', answer: '汗', options: ['史', '汗', '天', '青'], title: '过零丁洋', author: '文天祥', dynasty: '宋', difficulty: 'hard' },
  { id: 87, line: '山外青山___外楼', blank: '___', answer: '楼', options: ['阁', '楼', '亭', '台'], title: '题临安邸', author: '林升', dynasty: '宋', difficulty: 'hard' },
  { id: 88, line: '暖___熏得游人醉', blank: '___', answer: '风', options: ['风', '雨', '露', '雪'], title: '题临安邸', author: '林升', dynasty: '宋', difficulty: 'hard' },
  { id: 89, line: '何当共剪西___烛', blank: '___', answer: '窗', options: ['门', '帘', '窗', '堂'], title: '夜雨寄北', author: '李商隐', dynasty: '唐', difficulty: 'hard' },
  { id: 90, line: '却___巴山夜雨时', blank: '___', answer: '话', options: ['说', '谈', '忆', '话'], title: '夜雨寄北', author: '李商隐', dynasty: '唐', difficulty: 'hard' },
  { id: 91, line: '两情若是___长时', blank: '___', answer: '久', options: ['久', '深', '长', '远'], title: '鹊桥仙', author: '秦观', dynasty: '宋', difficulty: 'hard' },
  { id: 92, line: '前不见古___', blank: '___', answer: '人', options: ['人', '客', '贤', '者'], title: '登幽州台歌', author: '陈子昂', dynasty: '唐', difficulty: 'hard' },
  { id: 93, line: '念天地之___悠', blank: '___', answer: '悠', options: ['深', '长', '悠', '远'], title: '登幽州台歌', author: '陈子昂', dynasty: '唐', difficulty: 'hard' },
  { id: 94, line: '___花不是无情物', blank: '___', answer: '落', options: ['残', '落', '飞', '飘'], title: '己亥杂诗', author: '龚自珍', dynasty: '清', difficulty: 'hard' },
  { id: 95, line: '化作春___更护花', blank: '___', answer: '泥', options: ['风', '土', '泥', '雨'], title: '己亥杂诗', author: '龚自珍', dynasty: '清', difficulty: 'hard' },
  { id: 96, line: '长___破浪会有时', blank: '___', answer: '风', options: ['桨', '舟', '帆', '风'], title: '行路难', author: '李白', dynasty: '唐', difficulty: 'hard' },
  { id: 97, line: '直挂___帆济沧海', blank: '___', answer: '云', options: ['风', '云', '长', '高'], title: '行路难', author: '李白', dynasty: '唐', difficulty: 'hard' },
  { id: 98, line: '此中有___意', blank: '___', answer: '真', options: ['真', '深', '妙', '清'], title: '饮酒', author: '陶渊明', dynasty: '东晋', difficulty: 'hard' },
  { id: 99, line: '___辨已忘言', blank: '___', answer: '欲', options: ['欲', '将', '想', '思'], title: '饮酒', author: '陶渊明', dynasty: '东晋', difficulty: 'hard' },
  { id: 100, line: '三___频烦天下计', blank: '___', answer: '顾', options: ['请', '求', '访', '顾'], title: '蜀相', author: '杜甫', dynasty: '唐', difficulty: 'hard' },
]

export default ENTRIES