import type { Riddle } from '@wordcore/types'

const RIDDLES: Riddle[] = [
  // ===== Easy (1-35) =====
  {
    id: 1,
    hint: '田里长木',
    answer: '果',
    options: ['田', '棵', '菜', '果'],
    explanation: '"田"上加"木"就是"果"，田里长出的果实。',
    difficulty: 'easy',
  },
  { id: 2, hint: '田边人', answer: '佃', options: ['田', '人', '细', '佃'], explanation: '"亻"（人）加"田"就是"佃"，指佃户。', difficulty: 'easy' },
  { id: 3, hint: '田边力', answer: '男', options: ['田', '力', '另', '男'], explanation: '"田"加"力"就是"男"，在田里出力的意思。', difficulty: 'easy' },
  { id: 4, hint: '田边土', answer: '里', options: ['田', '土', '埋', '里'], explanation: '"田"加"土"就是"里"，表示乡里。', difficulty: 'easy' },
  { id: 5, hint: '禾在火边', answer: '秋', options: ['禾', '火', '和', '秋'], explanation: '"禾"加"火"就是"秋"，秋天禾谷成熟。', difficulty: 'easy' },
  { id: 6, hint: '禾在口边', answer: '和', options: ['禾', '口', '秋', '和'], explanation: '"禾"加"口"就是"和"，表示和谐。', difficulty: 'easy' },
  { id: 7, hint: '二人在土上', answer: '坐', options: ['人', '土', '从', '坐'], explanation: '两个"人"在"土"上，就是"坐"。', difficulty: 'easy' },
  { id: 8, hint: '手在耳边', answer: '取', options: ['耳', '手', '联', '取'], explanation: '"耳"边加"又"（手）就是"取"。', difficulty: 'easy' },
  { id: 9, hint: '水边白', answer: '泊', options: ['白', '水', '泉', '泊'], explanation: '"氵"加"白"就是"泊"，表示停泊。', difficulty: 'easy' },
  { id: 10, hint: '水边去', answer: '法', options: ['去', '水', '清', '法'], explanation: '"氵"加"去"就是"法"。', difficulty: 'easy' },
  { id: 11, hint: '人在草木中', answer: '茶', options: ['草', '木', '花', '茶'], explanation: '"艹"+"人"+"木"组成"茶"。', difficulty: 'easy' },
  { id: 12, hint: '半甜半辣', answer: '辞', options: ['舌', '辛', '甜', '辞'], explanation: '"甜"的一半（舌）加"辣"的一半（辛）就是"辞"。', difficulty: 'easy' },
  { id: 13, hint: '又到村里', answer: '树', options: ['村', '又', '木', '树'], explanation: '"村"里有"又"加"木"就是"树"。', difficulty: 'easy' },
  { id: 14, hint: '花前柳后', answer: '节', options: ['花', '柳', '草', '节'], explanation: '"花"前半（艹）加"柳"后半（卩）就是"节"。', difficulty: 'easy' },
  { id: 15, hint: '水边也有', answer: '池', options: ['也', '他', '地', '池'], explanation: '"氵"（水边）加"也"就是"池"。', difficulty: 'easy' },
  { id: 16, hint: '点心上桌', answer: '占', options: ['点', '心', '站', '占'], explanation: '"点"字去掉下面的"火"，就是"占"。', difficulty: 'easy' },
  { id: 17, hint: '一人在内', answer: '肉', options: ['人', '内', '大', '肉'], explanation: '"人"进入"内"就是"肉"。', difficulty: 'easy' },
  { id: 18, hint: '门前有口', answer: '问', options: ['门', '口', '闷', '问'], explanation: '"门"加"口"就是"问"。', difficulty: 'easy' },
  { id: 19, hint: '天上一口', answer: '吞', options: ['天', '口', '蚕', '吞'], explanation: '"天"加"口"就是"吞"，一口吞掉天。', difficulty: 'easy' },
  { id: 20, hint: '羊太大了', answer: '美', options: ['羊', '大', '群', '美'], explanation: '"羊"加"大"就是"美"。', difficulty: 'easy' },
  { id: 21, hint: '鱼和羊', answer: '鲜', options: ['鱼', '羊', '洋', '鲜'], explanation: '"鱼"加"羊"就是"鲜"，鱼羊同煮味道鲜美。', difficulty: 'easy' },
  { id: 22, hint: '角上顶刀，旁边有牛', answer: '解', options: ['角', '刀', '牛', '解'], explanation: '"角"加"刀"加"牛"组成"解"，分解之意。', difficulty: 'easy' },
  { id: 23, hint: '田里一条虫', answer: '虽', options: ['田', '虫', '虾', '虽'], explanation: '"口"（田形）加"虫"就是"虽"。', difficulty: 'easy' },
  { id: 24, hint: '洞穴里有狗', answer: '突', options: ['穴', '狗', '空', '突'], explanation: '"穴"加"犬"（狗）就是"突"，突然窜出。', difficulty: 'easy' },
  { id: 25, hint: '门里有人探头看', answer: '闪', options: ['门', '人', '间', '闪'], explanation: '"门"里加"人"就是"闪"，一闪而过。', difficulty: 'easy' },
  { id: 26, hint: '少了一撇', answer: '小', options: ['少', '多', '大', '小'], explanation: '"少"字去掉一撇就是"小"。', difficulty: 'easy' },
  { id: 27, hint: '夕上横', answer: '歹', options: ['夕', '一', '死', '歹'], explanation: '"夕"字加一横就是"歹"，表示凶恶。', difficulty: 'easy' },
  { id: 28, hint: '大人出门了', answer: '一', options: ['大', '人', '天', '一'], explanation: '"大"中的"人"出门了，剩下"一"。', difficulty: 'easy' },
  { id: 29, hint: '天被口吃了', answer: '吴', options: ['天', '口', '吞', '吴'], explanation: '"口"加"天"就是"吴"。', difficulty: 'easy' },
  { id: 30, hint: '竹下有寺', answer: '等', options: ['竹', '寺', '持', '等'], explanation: '"⺮"加"寺"就是"等"，等待之意。', difficulty: 'easy' },
  { id: 31, hint: '张口结舌', answer: '括', options: ['舌', '张', '刮', '括'], explanation: '"扌"加"舌"就是"括"，表示总括。', difficulty: 'easy' },
  { id: 32, hint: '马在跑', answer: '驰', options: ['马', '路', '跑', '驰'], explanation: '"马"加"也"就是"驰"，奔驰。', difficulty: 'easy' },
  { id: 33, hint: '木上加一点', answer: '术', options: ['木', '水', '述', '术'], explanation: '"木"加一点就是"术"，技术。', difficulty: 'easy' },
  { id: 34, hint: '水边两个木头', answer: '淋', options: ['水', '林', '森', '淋'], explanation: '"氵"加两个"木"（林）就是"淋"，淋雨。', difficulty: 'easy' },
  { id: 35, hint: '一人背着两块土', answer: '佳', options: ['人', '土', '挂', '佳'], explanation: '"亻"（人）加"圭"（两块土）就是"佳"。', difficulty: 'easy' },

  // ===== Medium (36-70) =====
  { id: 36, hint: '孔子登山', answer: '岳', options: ['山', '兵', '丘', '岳'], explanation: '"孔子"指"丘"，登山加"山"就是"岳"。', difficulty: 'medium' },
  { id: 37, hint: '一只黑狗，不叫不吼', answer: '默', options: ['黑', '熊', '犬', '默'], explanation: '"黑"加"犬"（狗）就是"默"，沉默不语。', difficulty: 'medium' },
  { id: 38, hint: '人旁有个人', answer: '从', options: ['众', '人', '个', '从'], explanation: '两"人"并排就是"从"，跟随。', difficulty: 'medium' },
  { id: 39, hint: '门外站着一人', answer: '们', options: ['门', '问', '闻', '们'], explanation: '"门"外加"亻"（人）就是"们"。', difficulty: 'medium' },
  { id: 40, hint: '有耳就能听到', answer: '闻', options: ['门', '问', '闷', '闻'], explanation: '"门"里有"耳"就是"闻"，听闻。', difficulty: 'medium' },
  { id: 41, hint: '池中无水', answer: '也', options: ['地', '他', '池', '也'], explanation: '"池"去掉三点水（氵）就是"也"。', difficulty: 'medium' },
  { id: 42, hint: '一人一口', answer: '合', options: ['拿', '口', '哈', '合'], explanation: '"人"+"一"+"口"合起来就是"合"。', difficulty: 'medium' },
  { id: 43, hint: '人在云上走', answer: '会', options: ['云', '运', '人', '会'], explanation: '"人"在"云"上，就是"会"。', difficulty: 'medium' },
  { id: 44, hint: '自大一点', answer: '臭', options: ['自', '大', '因', '臭'], explanation: '"自"+"大"加一点就是"臭"。', difficulty: 'medium' },
  { id: 45, hint: '一口咬掉牛尾巴', answer: '告', options: ['牛', '先', '口', '告'], explanation: '"牛"去掉尾巴（丨），加上"口"就是"告"。', difficulty: 'medium' },
  { id: 46, hint: '一口吃掉了牛头', answer: '牢', options: ['牛', '家', '羊', '牢'], explanation: '"宀"加"牛"就是"牢"，牛被关在棚里。', difficulty: 'medium' },
  { id: 47, hint: '石头砸中皮球', answer: '破', options: ['石', '皮', '球', '破'], explanation: '"石"加"皮"就是"破"。', difficulty: 'medium' },
  { id: 48, hint: '两朵花，一对叶', answer: '华', options: ['花', '叶', '化', '华'], explanation: '"化"加"十"就是"华"，华丽、中华。', difficulty: 'medium' },
  { id: 49, hint: '木下加一点', answer: '未', options: ['木', '末', '来', '未'], explanation: '"木"下面多加一根短横就是"未"，未来。', difficulty: 'medium' },
  { id: 50, hint: '石上流水', answer: '泵', options: ['石', '水', '泉', '泵'], explanation: '"石"加"水"就是"泵"，水泵。', difficulty: 'medium' },
  { id: 51, hint: '山中有虎', answer: '彪', options: ['山', '虎', '风', '彪'], explanation: '"虎"字旁边加三撇就是"彪"，虎纹彪炳。', difficulty: 'medium' },
  { id: 52, hint: '小河无水', answer: '可', options: ['小', '河', '水', '可'], explanation: '"河"去掉"氵"（水）就是"可"。', difficulty: 'medium' },
  { id: 53, hint: '一个人，两个耳朵', answer: '耸', options: ['人', '耳', '立', '耸'], explanation: '"从"（两个"人"）加"耳"就是"耸"，高耸入云。', difficulty: 'medium' },
  { id: 54, hint: '人在山旁', answer: '仙', options: ['山', '人', '出', '仙'], explanation: '"人"在"山"旁就是"仙"，山中有仙人。', difficulty: 'medium' },
  { id: 55, hint: '二三四五六七八九', answer: '缺', options: ['少', '缺', '十', '全'], explanation: '缺"一"少"十"，谜底就是"缺"。', difficulty: 'medium' },
  { id: 56, hint: '一半是水，一半是火', answer: '淡', options: ['水', '火', '炎', '淡'], explanation: '"氵"加"火"加两个"火"——"淡"字两边水火交融。', difficulty: 'medium' },
  { id: 57, hint: '用心记住', answer: '乙', options: ['心', '记', '亿', '乙'], explanation: '"忆"去掉"忄"（用心），剩下"乙"。', difficulty: 'medium' },
  { id: 58, hint: '屋顶下有猪', answer: '家', options: ['屋', '猪', '安', '家'], explanation: '"宀"（屋顶）加"豕"（猪）就是"家"。', difficulty: 'medium' },
  { id: 59, hint: '一点一横长，口字在中央，大口不封口，小口里面藏', answer: '高', options: ['高', '亮', '亭', '京'], explanation: '亠+口+冂+口=高，标准字形分解。', difficulty: 'medium' },
  { id: 60, hint: '上边草，下边草，中间藏颗黑葡萄', answer: '蒜', options: ['草', '花', '葡', '蒜'], explanation: '"艹"+"祘"（两个"示"）= 蒜，像两串黑葡萄。', difficulty: 'medium' },
  { id: 61, hint: '口中含玉', answer: '国', options: ['口', '玉', '王', '国'], explanation: '"口"里加"玉"就是"国"。', difficulty: 'medium' },
  { id: 62, hint: '一把短刀', answer: '匕', options: ['刀', '剑', '首', '匕'], explanation: '"匕"就是匕首的形状。', difficulty: 'medium' },
  { id: 63, hint: '四面围墙', answer: '口', options: ['中', '田', '日', '口'], explanation: '四面有墙围成的方形就是"口"。', difficulty: 'medium' },
  { id: 64, hint: '十加八', answer: '木', options: ['十', '八', '本', '木'], explanation: '"十"字加"八"字形状就是"木"。', difficulty: 'medium' },
  { id: 65, hint: '春天少了太阳，加上水', answer: '泰', options: ['春', '日', '水', '泰'], explanation: '"春"去掉"日"（太阳）加上"水"就是"泰"。', difficulty: 'medium' },
  { id: 66, hint: '土上加土', answer: '圭', options: ['土', '地', '上', '圭'], explanation: '"土"加"土"就是"圭"，古代玉器。', difficulty: 'medium' },
  { id: 67, hint: '太阳出来月亮落', answer: '明', options: ['日', '月', '暗', '明'], explanation: '"日"（太阳）加"月"（月亮）就是"明"。', difficulty: 'medium' },
  { id: 68, hint: '心中只有草', answer: '芯', options: ['心', '思', '想', '芯'], explanation: '"艹"（草）加"心"就是"芯"，灯芯、花芯。', difficulty: 'medium' },
  { id: 69, hint: '一人在内还有大', answer: '因', options: ['人', '大', '内', '因'], explanation: '"大"字里装进"人"就是"因"，因为。', difficulty: 'medium' },
  { id: 70, hint: '天上一横，地下一横，人在中间站', answer: '立', options: ['天', '地', '人', '立'], explanation: '一点一横在上，两点在下，下面一横——"立"字。', difficulty: 'medium' },

  // ===== Hard (71-100) =====
  { id: 71, hint: '半部春秋', answer: '秦', options: ['春', '秋', '泰', '秦'], explanation: '"春"的上半（𡗗=三+人）加"秋"的左半（禾）合为"秦"。', difficulty: 'hard' },
  { id: 72, hint: '半推半就', answer: '扰', options: ['推', '就', '掠', '扰'], explanation: '"推"的左边（扌）加"就"的右边（尤）就是"扰"。', difficulty: 'hard' },
  { id: 73, hint: '狗仗人势', answer: '伏', options: ['狗', '仗', '伐', '伏'], explanation: '"亻"（人）加"犬"（狗）就是"伏"，潜伏。', difficulty: 'hard' },
  { id: 74, hint: '青一块，紫一块', answer: '素', options: ['青', '紫', '素', '色'], explanation: '"青"的上半（⻘）加"紫"的下半（糸）合为"素"。', difficulty: 'hard' },
  { id: 75, hint: '身残心不残', answer: '息', options: ['身', '心', '自', '息'], explanation: '"身残"取"自"（自己），"心不残"取"心"，合为"息"。', difficulty: 'hard' },
  { id: 76, hint: '火烧横山', answer: '灵', options: ['火', '山', '雪', '灵'], explanation: '"火"加"彐"（横山）就是"灵"，灵感。', difficulty: 'hard' },
  { id: 77, hint: '无角牛', answer: '午', options: ['牛', '羊', '生', '午'], explanation: '"牛"字去掉头顶的撇（角），就是"午"。', difficulty: 'hard' },
  { id: 78, hint: '家中一口田', answer: '富', options: ['家', '田', '福', '富'], explanation: '"宀"+"一"+"口"+"田"合为"富"，富有。', difficulty: 'hard' },
  { id: 79, hint: '口吞十心', answer: '思', options: ['口', '心', '十', '思'], explanation: '"十"+"口"+"心"合起来就是"思"，思考。', difficulty: 'hard' },
  { id: 80, hint: '三面有墙，中间有个娃', answer: '匹', options: ['三', '儿', '区', '匹'], explanation: '"匚"（三面墙）加"儿"（小孩）就是"匹"。', difficulty: 'hard' },
  { id: 81, hint: '两个半月', answer: '羽', options: ['两', '半', '月', '羽'], explanation: '两个"习"（半月形）组成"羽"，羽毛。', difficulty: 'hard' },
  { id: 82, hint: '九十八', answer: '杂', options: ['九', '十', '八', '杂'], explanation: '"十"+"八"是"木"，再加"九"就是"杂"。', difficulty: 'hard' },
  { id: 83, hint: '太阳西升', answer: '晒', options: ['日', '西', '晴', '晒'], explanation: '"西"加"日"（太阳）就是"晒"。', difficulty: 'hard' },
  { id: 84, hint: '雨下田里', answer: '雷', options: ['雨', '田', '电', '雷'], explanation: '"雨"加"田"就是"雷"。', difficulty: 'hard' },
  { id: 85, hint: '一大二小', answer: '奈', options: ['大', '二', '小', '奈'], explanation: '"大"+"二"+"小"合为"奈"，无奈。', difficulty: 'hard' },
  { id: 86, hint: '白加王', answer: '皇', options: ['白', '王', '玉', '皇'], explanation: '"白"加"王"就是"皇"，皇帝。', difficulty: 'hard' },
  { id: 87, hint: '刀上有点血', answer: '刃', options: ['刀', '切', '分', '刃'], explanation: '"刀"上加一点就是"刃"，刀刃。', difficulty: 'hard' },
  { id: 88, hint: '两只狗张着口', answer: '哭', options: ['犬', '吠', '怒', '哭'], explanation: '两个"口"加"犬"（狗）就是"哭"。', difficulty: 'hard' },
  { id: 89, hint: '有草是水果，有水是大海', answer: '每', options: ['草', '海', '莓', '每'], explanation: '"每"加"艹"是"莓"（草莓），加"氵"是"海"。共同部分就是"每"。', difficulty: 'hard' },
  { id: 90, hint: '白在王上头', answer: '皇', options: ['王', '白', '玉', '皇'], explanation: '"白"在"王"上面就是"皇"。', difficulty: 'hard' },
  { id: 91, hint: '一在火上', answer: '灭', options: ['一', '火', '灾', '灭'], explanation: '"一"在"火"上盖住火焰，就是"灭"。', difficulty: 'hard' },
  { id: 92, hint: '一人一口水', answer: '洽', options: ['人', '口', '水', '洽'], explanation: '"氵"（水）加"合"（人+一+口）就是"洽"，融洽。', difficulty: 'hard' },
  { id: 93, hint: '木头上放块石头，下面一江水', answer: '染', options: ['木', '石', '江', '染'], explanation: '"木"加"九"加"氵"（水）就是"染"，染色。九像石头。', difficulty: 'hard' },
  { id: 94, hint: '人牵一头牛', answer: '件', options: ['人', '牛', '牵', '件'], explanation: '"亻"（人）加"牛"就是"件"，一件两件。', difficulty: 'hard' },
  { id: 95, hint: '天大，地大，人更大，人在大里面', answer: '因', options: ['天', '大', '人', '因'], explanation: '"大"里面加"人"就是"因"，人在大之中。', difficulty: 'hard' },
  { id: 96, hint: '口咬一根木', answer: '束', options: ['口', '木', '棍', '束'], explanation: '"木"加"口"（咬住）就是"束"，约束。', difficulty: 'hard' },
  { id: 97, hint: '一人握着两把戈', answer: '我', options: ['人', '戈', '战', '我'], explanation: '古文字中"我"像一个人拿着武器。"手"加"戈"为"我"。', difficulty: 'hard' },
  { id: 98, hint: '水边不见水，山头不见山', answer: '雨', options: ['水', '山', '雪', '雨'], explanation: '"雨"字里面既不像水也不像山，但中间一竖像雨丝，四点像雨滴。', difficulty: 'hard' },
  { id: 99, hint: '房子下面有女人', answer: '安', options: ['房', '女', '家', '安'], explanation: '"宀"（房子）加"女"就是"安"，安全、平安。', difficulty: 'hard' },
  { id: 100, hint: '两座金山叠一起，谁知还多了一座', answer: '鑫', options: ['金', '钱', '鑫', '银'], explanation: '三个"金"叠在一起就是"鑫"，财富极多。', difficulty: 'hard' },
]

export default RIDDLES
